export declare const PACKAGE_NAME: "@agentbadge/database";
export declare const PACKAGE_VERSION: "0.1.0";
export type { Contract } from "./prisma/contract.d.js";
export { createDatabase } from "./database.js";
export type { Database, DatabaseConfig } from "./database.js";
export { Repository } from "./repository.js";
export { InMemoryChatSubscriptionStore, InMemoryScanResultStore, InMemoryStore, } from "./store.js";
export type { ChatSubscription, ChatSubscriptionCreate, ChatSubscriptionStore, ChatSubscriptionUpdate, Event, EventCreate, EventUpdate, ScanResult, ScanResultCreate, ScanResultStore, ScanResultUpdate, Store, } from "./store.js";
export { EventRepository } from "./repositories/event-repository.js";
export { ScanResultRepository } from "./repositories/scan-result-repository.js";
export { ChatSubscriptionRepository } from "./repositories/chat-subscription-repository.js";
export type { PrismaDb } from "./repositories/event-repository.js";
