import type { RuleDescription } from "./index";

export const actionabilityRules: RuleDescription[] = [
  {
    rule_id: "AB-007",
    category: "actionability",
    icon: "🔄",
    title: "Guide and API Consistency",
    short_description: "Your agent guide and your API specification describe the same endpoints.",
    user_value: "If your guide says one thing but your API does another, agents will fail and avoid your service.",
    wrong_example: "Guide mentions endpoints that don't exist in the API spec, or vice versa.",
    right_example: "Guide and API spec are perfectly aligned — what agents read is what they get.",
    effort_hint: "moderate",
    estimated_cost: "$10-50",
  },
  {
    rule_id: "AB-008",
    category: "actionability",
    icon: "🔑",
    title: "Authentication Declared",
    short_description: "Your site declares its authentication method in a machine-readable way.",
    user_value: "Agents need to know how to authenticate before they can use your API. Without this, they're locked out.",
    wrong_example: "No machine-readable auth info. Agents don't know if they need API keys, OAuth, or something else.",
    right_example: "Authentication method is clearly declared, so agents know exactly how to get access.",
    effort_hint: "moderate",
    estimated_cost: "$10-50",
  },
  {
    rule_id: "AB-009",
    category: "actionability",
    icon: "🧩",
    title: "Capability Coverage",
    short_description: "Your agent guide covers all the capabilities your service offers.",
    user_value: "If your guide only mentions half your features, agents will only use half your service.",
    wrong_example: "Guide only covers 3 out of 10 available features.",
    right_example: "Guide covers all capabilities, so agents can use everything you offer.",
    effort_hint: "moderate",
    estimated_cost: "$10-50",
  },
  {
    rule_id: "AB-074",
    category: "actionability",
    icon: "🤝",
    title: "A2A Agent Card Published",
    short_description: "Your agent publishes a /.well-known/agent-card.json file so other agents can discover its capabilities via the A2A protocol.",
    user_value: "Agent Cards let other agents know what your agent can do, enabling autonomous discovery and inter-agent collaboration.",
    wrong_example: "No /.well-known/agent-card.json exists. Other agents cannot discover your agent's A2A capabilities.",
    right_example: "A valid agent-card.json is published at /.well-known/ with agent metadata per the A2A specification.",
    effort_hint: "quick",
    estimated_cost: "$0",
  },
  {
    rule_id: "AB-075",
    category: "actionability",
    icon: "✅",
    title: "A2A Agent Card Verified",
    short_description: "Your agent-card.json includes all required fields: name, description, url, and capabilities.",
    user_value: "A complete Agent Card ensures other agents can properly identify and interact with your agent.",
    wrong_example: "Agent card exists but is missing required fields like capabilities or url, making it unusable.",
    right_example: "Agent card includes name, description, url, and capabilities — all required A2A fields present.",
    effort_hint: "quick",
    estimated_cost: "$0",
  },
  {
    rule_id: "AB-085",
    category: "actionability",
    icon: "🔌",
    title: "MCP Server Name Present",
    short_description: "Your MCP server's initialize response includes serverInfo.name, allowing agents to identify the server.",
    user_value: "Agents need to know which MCP server they're connected to for tool routing and debugging.",
    wrong_example: "MCP initialize response has no serverInfo.name. Agents can't identify the server.",
    right_example: "MCP initialize response includes serverInfo.name as a non-empty string.",
    effort_hint: "quick",
    estimated_cost: "$0",
  },
  {
    rule_id: "AB-086",
    category: "actionability",
    icon: "🔐",
    title: "MCP Auth Discovery Resolves",
    short_description: "If your MCP descriptor declares authentication, the auth URL is reachable and returns valid metadata.",
    user_value: "Agents need to resolve auth requirements before calling MCP tools. Broken auth discovery blocks all tool access.",
    wrong_example: "MCP descriptor declares auth but the auth URL returns 404 or is unreachable.",
    right_example: "MCP auth discovery URL returns 200 with valid authentication metadata.",
    effort_hint: "moderate",
    estimated_cost: "$10-50",
  },
  {
    rule_id: "AB-146",
    category: "actionability",
    icon: "📝",
    title: "Operation descriptions",
    short_description: "Every OpenAPI operation has a description or summary.",
    user_value: "Agents need text descriptions to understand what each endpoint does — without them, operations are opaque.",
    wrong_example: "paths: { /charges: { get: {} } }",
    right_example: "paths: { /charges: { get: { description: 'List all charges with pagination' } } }",
    effort_hint: "quick",
    estimated_cost: "$0",
    severity: "medium",
  },
  {
    rule_id: "AB-159",
    category: "actionability",
    icon: "⚖️",
    title: "Business constraints documented",
    short_description: "Business rules (refund windows, cancellation policies) are documented.",
    user_value: "Agents need to know business constraints to avoid invalid actions (e.g. refunding after 180 days).",
    wrong_example: "// no constraints mentioned",
    right_example: 'agent-guide.json: { "constraints": { "refunds": "180 days", "cancellation": "before capture" } }',
    effort_hint: "quick",
    estimated_cost: "$0",
    severity: "low",
  },
  {
    rule_id: "AB-162",
    category: "actionability",
    icon: "💓",
    title: "Heartbeat.md availability",
    short_description: "Your site serves /heartbeat.md with YAML frontmatter, providing a periodic check-in routine for AI agents.",
    user_value: "AI agents can periodically check your service health and status via a machine-readable heartbeat endpoint, enabling self-healing workflows.",
    wrong_example: "GET /heartbeat.md → 404",
    right_example: "---\nstatus: operational\nlast_check: 2026-09-07\n---\n# Heartbeat\nService is operational.",
    effort_hint: "quick",
    estimated_cost: "$0",
    severity: "low",
  },
  {
    rule_id: "AB-166",
    category: "actionability",
    icon: "➡️",
    title: "next_call pattern in API responses",
    short_description: "Your OpenAPI spec includes a next_call field in response schemas with method, path, and why to guide agents to the next request.",
    user_value: "AI agents can follow a chain of API calls autonomously without hardcoding navigation logic, improving actionability and reducing integration friction.",
    wrong_example: '{"data": {"id": 123}}',
    right_example: '{"data": {"id": 123}, "next_call": {"method": "GET", "path": "/api/v1/items/123", "why": "Fetch item details"}}',
    effort_hint: "moderate",
    estimated_cost: "$0",
    severity: "low",
  }
];
