import type { RuleDescription } from "./index";

export const botAuthRules: RuleDescription[] = [
  {
    rule_id: "AB-023",
    category: "bot_auth",
    icon: "🔐",
    title: "MCP Auth Discovery",
    short_description: "Your MCP server's authentication info is discoverable by agents.",
    user_value: "Agents need to find auth info before connecting to your MCP server. Without discovery, they can't authenticate.",
    wrong_example: "MCP server requires auth but doesn't publish how to get it.",
    right_example: "Auth discovery is available, so agents know how to authenticate.",
    effort_hint: "moderate",
    estimated_cost: "$10-50",
  },
  {
    rule_id: "AB-058",
    category: "bot_auth",
    icon: "✍️",
    title: "Bot Signatures Directory",
    short_description: "Your site has a directory of bot signatures for verifying AI agent identities.",
    user_value: "A signatures directory lets you verify which bot is making a request, enabling trust-based access control.",
    wrong_example: "No signatures directory. You can't tell which bot is calling your API.",
    right_example: "A signatures directory lets you identify and trust specific bots.",
    effort_hint: "complex",
    estimated_cost: "$100+",
  },
  {
    rule_id: "AB-059",
    category: "bot_auth",
    icon: "👥",
    title: "Bot Directory Members",
    short_description: "Your bot signatures directory has valid, recognized members.",
    user_value: "A directory with invalid members is useless. Valid members enable real bot identification.",
    wrong_example: "Bot directory exists but members are invalid or unrecognized.",
    right_example: "All members in the bot directory are valid and recognized.",
    effort_hint: "moderate",
    estimated_cost: "$10-50",
  },
  {
    rule_id: "AB-060",
    category: "bot_auth",
    icon: "🔑",
    title: "Bot Public Keys",
    short_description: "Public keys for verified bots are reachable and valid.",
    user_value: "Public keys are needed to verify bot signatures. If they're unreachable, signature verification fails.",
    wrong_example: "Public keys are listed but unreachable. Signature verification fails.",
    right_example: "All public keys are reachable and valid for signature verification.",
    effort_hint: "moderate",
    estimated_cost: "$10-50",
  },
  {
    rule_id: "AB-063",
    category: "bot_auth",
    icon: "🛡️",
    title: "Protected Resource Metadata",
    short_description: "Your site publishes metadata about what resources are protected and how.",
    user_value: "This metadata tells agents which endpoints need authentication and what type, so they know before making requests.",
    wrong_example: "No protected resource metadata. Agents don't know which endpoints need auth.",
    right_example: "Protected resource metadata clearly indicates which endpoints need auth and how.",
    effort_hint: "moderate",
    estimated_cost: "$10-50",
  },
  {
    rule_id: "AB-067",
    category: "bot_auth",
    icon: "📜",
    title: "Web Bot Auth Directory",
    short_description: "Your site has a directory for web-based bot authentication using HTTP message signatures.",
    user_value: "This enables a standardized way for bots to prove their identity when making HTTP requests to your site.",
    wrong_example: "No web bot auth directory. Bots can't prove who they are when calling your API.",
    right_example: "A web bot auth directory enables standardized bot identification.",
    effort_hint: "complex",
    estimated_cost: "$100+",
  },
  {
    rule_id: "AB-128",
    category: "bot_auth",
    icon: "🔐",
    title: "OAuth2 preferred over static API keys",
    short_description: "Your API uses OAuth2 security schemes instead of static API keys.",
    user_value: "OAuth2 enables session-scoped, revocable tokens — agents can authenticate without permanent shared secrets. Static API keys never expire and are equivalent to sharing a password.",
    wrong_example: "OpenAPI security scheme: { type: 'apiKey', in: 'header', name: 'X-API-Key' }",
    right_example: "OpenAPI security scheme: { type: 'oauth2', flows: { clientCredentials: { tokenUrl: '/oauth/token', scopes: { read: 'Read access' } } } }",
    effort_hint: "moderate",
    estimated_cost: "$0",
  },
  {
    rule_id: "AB-129",
    category: "bot_auth",
    icon: "🔐",
    title: "Credentials via headers not query params",
    short_description: "API keys and tokens are passed in headers, not query parameters.",
    user_value: "Query parameter credentials get logged in access logs, browser history, and referrer headers. Header-based credentials are never logged or cached.",
    wrong_example: "GET /api/data?api_key=secret123",
    right_example: "GET /api/data with header: Authorization: Bearer token123",
    effort_hint: "quick",
    estimated_cost: "$0",
  },
  {
    rule_id: "AB-130",
    category: "bot_auth",
    icon: "🔐",
    title: "OAuth scopes defined",
    short_description: "Your OAuth metadata declares scopes_supported.",
    user_value: "Scopes let agents request narrowly-permissioned tokens. Without scopes, agents get all-or-nothing access, which is unsafe for autonomous operations.",
    wrong_example: "OAuth metadata has no scopes_supported field.",
    right_example: "OAuth metadata: { scopes_supported: ['read', 'write', 'admin'] }",
    effort_hint: "quick",
    estimated_cost: "$0",
  },
  {
    rule_id: "AB-131",
    category: "bot_auth",
    icon: "🔐",
    title: "Token revocation endpoint available",
    short_description: "Your OAuth metadata publishes a revocation_endpoint.",
    user_value: "Revocation lets agents and vaults invalidate compromised tokens immediately. Without revocation, a leaked token remains valid until expiry.",
    wrong_example: "OAuth metadata has no revocation_endpoint.",
    right_example: "OAuth metadata: { revocation_endpoint: 'https://api.example.com/oauth/revoke' }",
    effort_hint: "moderate",
    estimated_cost: "$0",
  },
  {
    rule_id: "AB-132",
    category: "bot_auth",
    icon: "🔐",
    title: "Token introspection supported",
    short_description: "Your OAuth metadata publishes an introspection_endpoint (optional).",
    user_value: "Introspection lets resource servers validate tokens in real-time, enabling immediate revocation and audit trails.",
    wrong_example: "OAuth metadata has no introspection_endpoint.",
    right_example: "OAuth metadata: { introspection_endpoint: 'https://api.example.com/oauth/introspect' }",
    effort_hint: "moderate",
    estimated_cost: "$0",
  },
  {
    rule_id: "AB-133",
    category: "bot_auth",
    icon: "🔐",
    title: "Private key JWT authentication",
    short_description: "Your token endpoint supports private_key_jwt auth method (optional).",
    user_value: "Private key JWT enables asymmetric client authentication — agents prove identity with a signed JWT instead of a shared secret, enabling non-repudiation.",
    wrong_example: "token_endpoint_auth_methods_supported: ['client_secret_basic']",
    right_example: "token_endpoint_auth_methods_supported: ['client_secret_basic', 'private_key_jwt']",
    effort_hint: "complex",
    estimated_cost: "$0",
  },
  {
    rule_id: "AB-134",
    category: "bot_auth",
    icon: "🔐",
    title: "Token Exchange (RFC 8693) supported",
    short_description: "Your OAuth metadata supports token-exchange grant type (optional).",
    user_value: "Token exchange lets agents trade one token for another with reduced scope — enabling delegation patterns where an agent acts on behalf of a user.",
    wrong_example: "grant_types_supported: ['client_credentials']",
    right_example: "grant_types_supported: ['client_credentials', 'urn:ietf:params:oauth:grant-type:token-exchange']",
    effort_hint: "complex",
    estimated_cost: "$0",
  },
  {
    rule_id: "AB-135",
    category: "bot_auth",
    icon: "🔐",
    title: "AAuth metadata endpoint available",
    short_description: "Your API publishes /.well-known/aauth.json with agent authorization metadata.",
    user_value: "AAuth metadata lets agents discover agent-specific auth flows, scope descriptions, and grant types — the foundation for agent-safe authentication.",
    wrong_example: "No /.well-known/aauth.json endpoint.",
    right_example: "GET /.well-known/aauth.json returns { scope_descriptions: [...] }",
    effort_hint: "moderate",
    estimated_cost: "$0",
  },
  {
    rule_id: "AB-136",
    category: "bot_auth",
    icon: "🔐",
    title: "Agent Authorization Grant supported",
    short_description: "Your OAuth metadata includes the agent_authorization grant type.",
    user_value: "The Agent Authorization Grant (IETF draft) is an OAuth 2.1 extension specifically for AI agents — enabling scoped, session-bound token issuance.",
    wrong_example: "grant_types_supported: ['client_credentials', 'refresh_token']",
    right_example: "grant_types_supported: ['client_credentials', 'urn:ietf:params:oauth:grant-type:agent_authorization']",
    effort_hint: "complex",
    estimated_cost: "$0",
  },
  {
    rule_id: "AB-137",
    category: "bot_auth",
    icon: "🔐",
    title: "AAuth scope descriptions published",
    short_description: "Your aauth.json publishes scope_descriptions (optional).",
    user_value: "Scope descriptions let agents understand what each scope does before requesting it — enabling autonomous, informed consent.",
    wrong_example: "aauth.json: { } (no scope_descriptions)",
    right_example: "aauth.json: { scope_descriptions: [{ scope: 'read', description: 'Read-only access to resources' }] }",
    effort_hint: "quick",
    estimated_cost: "$0",
  },
  {
    rule_id: "AB-138",
    category: "bot_auth",
    icon: "🔐",
    title: "DPoP token binding supported",
    short_description: "Your OAuth metadata supports DPoP (RFC 9449) for token binding (optional).",
    user_value: "DPoP binds access tokens to a cryptographic key held by the client, preventing token replay attacks even if a token is leaked.",
    wrong_example: "No dpop_signing_alg_values_supported in OAuth metadata.",
    right_example: "OAuth metadata: { dpop_signing_alg_values_supported: ['ES256', 'RS256'] }",
    effort_hint: "complex",
    estimated_cost: "$0",
  },
  {
    rule_id: "AB-139",
    category: "bot_auth",
    icon: "🔐",
    title: "mTLS-bound access tokens",
    short_description: "Your OAuth metadata supports mTLS certificate-bound tokens (optional).",
    user_value: "mTLS token binding (RFC 8705) binds access tokens to a client certificate, providing the strongest form of sender-constrained tokens.",
    wrong_example: "No tls_client_certificate_bound_access_tokens in OAuth metadata.",
    right_example: "OAuth metadata: { tls_client_certificate_bound_access_tokens: true }",
    effort_hint: "complex",
    estimated_cost: "$0",
  },
  {
    rule_id: "AB-141",
    category: "bot_auth",
    icon: "🔐",
    title: "Short-lived access tokens",
    short_description: "Your token endpoint returns expires_in with access tokens.",
    user_value: "Short-lived tokens limit the blast radius of token theft. Agents can request new tokens as needed, but a stolen token expires quickly.",
    wrong_example: "Token response: { access_token: 'abc', token_type: 'Bearer' } (no expires_in)",
    right_example: "Token response: { access_token: 'abc', token_type: 'Bearer', expires_in: 3600 }",
    effort_hint: "quick",
    estimated_cost: "$0",
  },
  {
    rule_id: "AB-142",
    category: "bot_auth",
    icon: "🔐",
    title: "Refresh token rotation supported",
    short_description: "Your OAuth metadata includes refresh_token in grant_types_supported (optional).",
    user_value: "Refresh token rotation lets agents maintain long-running sessions without re-authenticating, while each refresh issues a new token — limiting replay window.",
    wrong_example: "grant_types_supported: ['client_credentials']",
    right_example: "grant_types_supported: ['client_credentials', 'refresh_token']",
    effort_hint: "moderate",
    estimated_cost: "$0",
  },
  {
    rule_id: "AB-143",
    category: "bot_auth",
    icon: "🔐",
    title: "Token revocation endpoint reachable",
    short_description: "Your credential security analysis confirms revocation endpoint is supported.",
    user_value: "A reachable revocation endpoint lets agents and credential vaults invalidate tokens immediately upon detecting compromise.",
    wrong_example: "credential_security: { revocationSupported: false }",
    right_example: "credential_security: { revocationSupported: true }",
    effort_hint: "moderate",
    estimated_cost: "$0",
  },
  {
    rule_id: "AB-145",
    category: "bot_auth",
    icon: "🔐",
    title: "No static API keys in OpenAPI security",
    short_description: "Your OpenAPI spec does not use apiKey security schemes.",
    user_value: "Static API keys are permanent shared secrets — the opposite of session-scoped auth. Removing them from OpenAPI security forces OAuth2 adoption.",
    wrong_example: "OpenAPI: { components: { securitySchemes: { ApiKey: { type: 'apiKey', in: 'header' } } } }",
    right_example: "OpenAPI: { components: { securitySchemes: { OAuth2: { type: 'oauth2', flows: {...} } } } }",
    effort_hint: "moderate",
    estimated_cost: "$0",
  },
  {
    rule_id: "AB-153",
    category: "bot_auth",
    icon: "🔐",
    title: "Authentication clarity",
    short_description: "Security schemes are declared in the OpenAPI spec.",
    user_value: "Without declared authentication, agents cannot determine how to authenticate — they are blocked.",
    wrong_example: "openapi.json has no components.securitySchemes",
    right_example: "components: { securitySchemes: { OAuth2: { type: 'oauth2', flows: { authorizationCode: {...} } } } }",
    effort_hint: "moderate",
    estimated_cost: "$0",
    severity: "critical",
  }
];
