import type { RuleDescription } from "./index";

export const contentNegotiationRules: RuleDescription[] = [
  {
    rule_id: "AB-015",
    category: "content_negotiation",
    icon: "🤖",
    title: "Agent User-Agent Format",
    short_description: "Your site serves appropriate content when an AI agent visits.",
    user_value: "When an AI agent visits your site, it should get content optimized for machines, not a web page designed for humans.",
    wrong_example: "AI agents get the same HTML as human visitors. They can't parse it efficiently.",
    right_example: "AI agents get clean, structured content optimized for their needs.",
    effort_hint: "moderate",
    estimated_cost: "$10-50",
  },
  {
    rule_id: "AB-016",
    category: "content_negotiation",
    icon: "📊",
    title: "JSON Format Support",
    short_description: "Your site returns JSON when an agent requests it.",
    user_value: "JSON is the universal language for APIs. If agents can't get JSON, they can't use your data.",
    wrong_example: "Requesting JSON always returns HTML. Agents can't extract data.",
    right_example: "Requesting JSON returns clean JSON data that agents can parse.",
    effort_hint: "moderate",
    estimated_cost: "$10-50",
  },
  {
    rule_id: "AB-017",
    category: "content_negotiation",
    icon: "📝",
    title: "Plain Text Format Support",
    short_description: "Your site returns plain text when an agent requests it.",
    user_value: "Some AI models work best with plain text. Offering it makes your content accessible to more agents.",
    wrong_example: "Only HTML and JSON available. Text-only AI models can't use your content.",
    right_example: "Plain text is available for AI models that prefer it.",
    effort_hint: "quick",
    estimated_cost: "$0",
  },
  {
    rule_id: "AB-018",
    category: "content_negotiation",
    icon: "⬇️",
    title: "Markdown Format Support",
    short_description: "Your site returns Markdown when an agent requests it.",
    user_value: "Markdown is the preferred format for many AI systems. Offering it makes your content easy to consume.",
    wrong_example: "No Markdown option. AI models have to convert from HTML, losing formatting.",
    right_example: "Markdown is available, preserving formatting for AI consumption.",
    effort_hint: "quick",
    estimated_cost: "$0",
  },
  {
    rule_id: "AB-019",
    category: "content_negotiation",
    icon: "🎯",
    title: "Preferred Format Selection",
    short_description: "Your site respects format preferences when agents specify what they want.",
    user_value: "When an agent says 'I prefer JSON over HTML', your site should honor that preference.",
    wrong_example: "Format preferences are ignored. Agents get whatever the server decides.",
    right_example: "Format preferences are respected, so agents get exactly what they asked for.",
    effort_hint: "moderate",
    estimated_cost: "$10-50",
  },
  {
    rule_id: "AB-028",
    category: "content_negotiation",
    icon: "🔀",
    title: "Vary Header",
    short_description: "Your site tells caches that content varies based on the requested format.",
    user_value: "Without a Vary header, caches may serve the wrong format to agents — JSON to someone who asked for HTML.",
    wrong_example: "No Vary header. Caches serve stale or wrong formats.",
    right_example: "Vary header ensures each agent gets the correct format from caches.",
    effort_hint: "quick",
    estimated_cost: "$0",
  },
  {
    rule_id: "AB-029",
    category: "content_negotiation",
    icon: "📍",
    title: "No Redirect on Negotiation",
    short_description: "Your site serves the requested format directly without redirecting.",
    user_value: "Redirects slow agents down and can break some clients. Direct responses are faster and more reliable.",
    wrong_example: "Requesting JSON redirects to a different URL. Some agents can't follow redirects.",
    right_example: "The requested format is served directly at the same URL.",
    effort_hint: "quick",
    estimated_cost: "$0",
  }
];
