import type { RuleDescription } from "./index";

export const discoveryRules: RuleDescription[] = [
  {
    rule_id: "AB-001",
    category: "discovery",
    icon: "🔍",
    title: "Robots.txt File",
    short_description: "Your site has a robots.txt file that tells crawlers and AI agents what they can access.",
    user_value: "Without this file, AI agents don't know which parts of your site they're allowed to read, and may skip your content entirely.",
    wrong_example: "No robots.txt file found. Agents assume nothing is allowed.",
    right_example: "A clear robots.txt welcomes AI agents to explore your content.",
    effort_hint: "quick",
    estimated_cost: "$0",
  },
  {
    rule_id: "AB-002",
    category: "discovery",
    icon: "🗺️",
    title: "Sitemap File",
    short_description: "Your site has a sitemap listing all important pages for agents to discover.",
    user_value: "A sitemap ensures AI agents find every page on your site, not just the ones they stumble upon.",
    wrong_example: "No sitemap. Agents only find pages through external links.",
    right_example: "A complete sitemap lists all 20+ pages for easy discovery.",
    effort_hint: "quick",
    estimated_cost: "$0",
  },
  {
    rule_id: "AB-003",
    category: "discovery",
    icon: "🧭",
    title: "Agent Guide",
    short_description: "Your site has a dedicated guide that tells AI agents what you offer and how to interact.",
    user_value: "An agent guide is your front door for AI visitors. Without it, agents don't know what your site does.",
    wrong_example: "No agent guide. AI agents have to guess what your site is about.",
    right_example: "A clear guide explains your services, capabilities, and how to interact.",
    effort_hint: "moderate",
    estimated_cost: "$10-50",
  },
  {
    rule_id: "AB-014",
    category: "discovery",
    icon: "📄",
    title: "LLMs.txt File",
    short_description: "Your site has an llms.txt file that provides a plain-text overview for large language models.",
    user_value: "LLMs read this file to quickly understand your site without parsing HTML. It's like a README for AI.",
    wrong_example: "No llms.txt. AI models have to parse your HTML and may miss key information.",
    right_example: "A concise llms.txt gives AI models everything they need in plain text.",
    effort_hint: "quick",
    estimated_cost: "$0",
  },
  {
    rule_id: "AB-061",
    category: "discovery",
    icon: "🔗",
    title: "Link Relationships",
    short_description: "Your homepage includes link headers that connect related resources together.",
    user_value: "Link headers help agents navigate your site by following relationships between pages, like a map.",
    wrong_example: "No link relationships. Agents can't discover related pages automatically.",
    right_example: "Links connect your guide, API docs, and sitemap so agents can explore everything.",
    effort_hint: "moderate",
    estimated_cost: "$10-50",
  },
  {
    rule_id: "AB-062",
    category: "discovery",
    icon: "📚",
    title: "API Catalog",
    short_description: "Your site publishes a catalog of all available APIs in a standard location.",
    user_value: "An API catalog lets agents discover everything they can do with your site in one place.",
    wrong_example: "No API catalog. Agents have to guess or search for available endpoints.",
    right_example: "A catalog lists all APIs with descriptions, so agents know exactly what's available.",
    effort_hint: "moderate",
    estimated_cost: "$10-50",
  },
  {
    rule_id: "AB-066",
    category: "discovery",
    icon: "🏷️",
    title: "Content Signals",
    short_description: "Your robots.txt declares preferences about how AI can use your content.",
    user_value: "Content signals let you control whether AI can train on, search, or use your content as input — protecting your rights.",
    wrong_example: "No content signals. AI systems assume default permissions, which may not match your wishes.",
    right_example: "Clear signals tell AI systems exactly what they can and can't do with your content.",
    effort_hint: "quick",
    estimated_cost: "$0",
  },
  {
    rule_id: "AB-068",
    category: "discovery",
    icon: "🌐",
    title: "DNS Agent Discovery",
    short_description: "Your domain has DNS records that help agents discover your services automatically.",
    user_value: "DNS-based discovery means agents can find you without prior knowledge of your URL — like a phone book for AI.",
    wrong_example: "No DNS discovery records. Agents can only find you if they already know your URL.",
    right_example: "DNS records announce your agent services to the world.",
    effort_hint: "moderate",
    estimated_cost: "$10-50",
  },
  {
    rule_id: "AB-110",
    category: "discovery",
    icon: "map",
    title: "Blog articles in AI sitemap",
    short_description: "AI sitemap includes blog/article URLs, not just static pages.",
    user_value: "AI agents discover your content through sitemaps. Including blog URLs ensures agents can find and reference your articles.",
    wrong_example: "ai-sitemap.xml only lists / and /about — missing /blog/* URLs.",
    right_example: "ai-sitemap.xml includes /blog/article-1, /blog/article-2 alongside static pages.",
    effort_hint: "moderate",
    estimated_cost: "$0",
  },
  {
    rule_id: "AB-111",
    category: "discovery",
    icon: "clock",
    title: "Crawl-delay directive in robots.txt",
    short_description: "robots.txt includes a Crawl-delay directive to control crawl rate.",
    user_value: "Crawl-delay prevents aggressive crawling that can overload your server and ensures agents respect your rate limits.",
    wrong_example: "robots.txt with no Crawl-delay directive.",
    right_example: "Crawl-delay: 1 in robots.txt.",
    effort_hint: "quick",
    estimated_cost: "$0",
  },
  {
    rule_id: "AB-113",
    category: "discovery",
    icon: "policy",
    title: "LLM policy file",
    short_description: "LLM usage policy published at /.well-known/llm-policy.json.",
    user_value: "An LLM policy file declares your terms for AI training, ingestion, and summarization, giving agents clear usage guidelines.",
    wrong_example: "No /.well-known/llm-policy.json endpoint.",
    right_example: "{ \"version\": \"1.0\", \"training\": \"allowed-with-attribution\", \"ingestion\": \"allowed\" } at /.well-known/llm-policy.json.",
    effort_hint: "moderate",
    estimated_cost: "$0",
  },
  {
    rule_id: "AB-114",
    category: "discovery",
    icon: "coverage",
    title: "AI sitemap content type coverage",
    short_description: "AI sitemap covers at least 50% of the URLs in the regular sitemap.",
    user_value: "If your AI sitemap only lists a fraction of your regular sitemap URLs, AI agents miss significant content. Coverage parity ensures discoverability.",
    wrong_example: "sitemap.xml has 100 URLs, ai-sitemap.xml has 10 URLs (10% coverage).",
    right_example: "sitemap.xml has 100 URLs, ai-sitemap.xml has 60 URLs (60% coverage).",
    effort_hint: "moderate",
    estimated_cost: "$0",
  },
  {
    rule_id: "AB-158",
    category: "discovery",
    icon: "🧭",
    title: "Capability list declared",
    short_description: "A capabilities list is present in agent-guide.",
    user_value: "Agents need a high-level overview of what the API can do before reading the full spec.",
    wrong_example: "// agent-guide has no capabilities array",
    right_example: 'agent-guide.json: { "capabilities": [{ "name": "Create charge", "description": "..." }] }',
    effort_hint: "quick",
    estimated_cost: "$0",
    severity: "medium",
  },
  {
    rule_id: "AB-161",
    category: "discovery",
    icon: "🤖",
    title: "AI-Agent Discovery meta tags",
    short_description: "Your HTML head declares ai-agent-discovery and ai-agent-onboarding meta tags pointing to machine-readable entry points.",
    user_value: "AI agents landing on any page immediately know where to find your llms.txt and onboarding guide, without guessing URL conventions.",
    wrong_example: "<head>… no AI-agent meta tags …</head>",
    right_example: '<meta name="ai-agent-discovery" content="https://example.com/llms.txt">\n<meta name="ai-agent-onboarding" content="https://example.com/skill.md">',
    effort_hint: "quick",
    estimated_cost: "$0",
    severity: "high",
  },
  {
    rule_id: "AB-165",
    category: "discovery",
    icon: "📡",
    title: "Agent feeds (JSON Feed 1.1 / RSS 2.0)",
    short_description: "Your site serves structured JSON Feed 1.1 or RSS 2.0 feeds at common paths like /agents.json, /jobs.rss, or /feed.json.",
    user_value: "AI agents can subscribe to your feeds instead of polling, enabling efficient discovery of new tasks, jobs, or marketplace items.",
    wrong_example: "GET /agents.json → 404",
    right_example: '{"version":"https://jsonfeed.org/version/1.1","items":[{"id":"task-1","title":"New task"}]}',
    effort_hint: "moderate",
    estimated_cost: "$0",
    severity: "low",
  }
];
