import type { RuleDescription } from "./index";

export const documentationRules: RuleDescription[] = [
  {
    rule_id: "AB-004",
    category: "documentation",
    icon: "📋",
    title: "API Specification",
    short_description: "Your site has a machine-readable API specification that agents can parse.",
    user_value: "An API spec is how agents understand what your API does, what parameters it accepts, and what it returns.",
    wrong_example: "No API specification. Agents can't use your API without guessing.",
    right_example: "A complete API specification tells agents exactly how to use your service.",
    effort_hint: "complex",
    estimated_cost: "$100+",
  },
  {
    rule_id: "AB-005",
    category: "documentation",
    icon: "🧪",
    title: "Agent Guide Schema Validation",
    short_description: "Your agent guide follows the expected format with all required fields.",
    user_value: "A valid agent guide means agents can reliably parse it. An invalid guide is worse than none — it causes errors.",
    wrong_example: "Agent guide exists but is missing required fields or has wrong format.",
    right_example: "Agent guide passes validation with all required fields properly filled.",
    effort_hint: "moderate",
    estimated_cost: "$10-50",
  },
  {
    rule_id: "AB-006",
    category: "documentation",
    icon: "🔌",
    title: "MCP Server Descriptor",
    short_description: "Your site advertises its MCP server so agents can discover and connect to it.",
    user_value: "MCP is the standard way agents interact with services. Without a descriptor, agents don't know you support it.",
    wrong_example: "No MCP descriptor. Agents don't know your site has an MCP server.",
    right_example: "MCP descriptor is discoverable, so agents can connect and use your tools.",
    effort_hint: "moderate",
    estimated_cost: "$10-50",
  },
  {
    rule_id: "AB-024",
    category: "documentation",
    icon: "📑",
    title: "Detailed LLMs File",
    short_description: "Your site has an extended llms-full.txt with comprehensive information for AI models.",
    user_value: "While llms.txt is a summary, llms-full.txt gives AI models the complete picture of your service.",
    wrong_example: "Only a basic llms.txt. AI models get a summary but miss important details.",
    right_example: "A comprehensive llms-full.txt gives AI models everything they need to understand your service.",
    effort_hint: "moderate",
    estimated_cost: "$10-50",
  },
  {
    rule_id: "AB-025",
    category: "documentation",
    icon: "📌",
    title: "LLMs File Linked from HTML",
    short_description: "Your homepage links to your llms.txt file so AI models can find it.",
    user_value: "Even if you have llms.txt, agents won't find it unless it's linked from your pages.",
    wrong_example: "llms.txt exists but isn't linked from any page. AI models may never find it.",
    right_example: "llms.txt is linked from your homepage, making it easy for AI to discover.",
    effort_hint: "quick",
    estimated_cost: "$0",
  },
  {
    rule_id: "AB-049",
    category: "documentation",
    icon: "📡",
    title: "RSS or Atom Feed",
    short_description: "Your site has an RSS or Atom feed for agents to subscribe to updates.",
    user_value: "Feeds let agents monitor your site for changes without crawling it repeatedly.",
    wrong_example: "No RSS feed. Agents have to re-crawl your site to check for updates.",
    right_example: "An RSS feed lets agents subscribe and get notified of new content automatically.",
    effort_hint: "moderate",
    estimated_cost: "$10-50",
  },
  {
    rule_id: "AB-052",
    category: "documentation",
    icon: "🖼️",
    title: "Social Preview Image",
    short_description: "Your site has a social preview image that appears when shared on social media or in AI responses.",
    user_value: "A preview image makes your site look professional when shared or cited by AI, increasing click-through rates.",
    wrong_example: "No social preview image. Links to your site look plain and get fewer clicks.",
    right_example: "A branded preview image appears whenever your site is shared or cited.",
    effort_hint: "quick",
    estimated_cost: "$0",
  },
  {
    rule_id: "AB-053",
    category: "documentation",
    icon: "⭐",
    title: "SVG Favicon",
    short_description: "Your site has a scalable SVG favicon that looks crisp at any size.",
    user_value: "SVG favicons look sharp on all devices and can be used by AI systems to represent your brand.",
    wrong_example: "Only a raster favicon. Looks blurry when scaled up.",
    right_example: "An SVG favicon stays crisp at any resolution.",
    effort_hint: "quick",
    estimated_cost: "$0",
  },
  {
    rule_id: "AB-054",
    category: "documentation",
    icon: "🔗",
    title: "Canonical URL",
    short_description: "Your pages have canonical URLs that tell agents which version is the official one.",
    user_value: "Canonical URLs prevent duplicate content issues and ensure agents reference the right page.",
    wrong_example: "No canonical URLs. Agents may index duplicate versions of your pages.",
    right_example: "Each page has a canonical URL, so agents know which version is official.",
    effort_hint: "quick",
    estimated_cost: "$0",
  },
  {
    rule_id: "AB-055",
    category: "documentation",
    icon: "📰",
    title: "RSS Feed Linked from HTML",
    short_description: "Your homepage links to your RSS feed so agents can discover it.",
    user_value: "Even if you have an RSS feed, agents won't find it unless it's linked from your pages.",
    wrong_example: "RSS feed exists but isn't linked. Agents may not discover it.",
    right_example: "RSS feed is linked from your homepage for easy discovery.",
    effort_hint: "quick",
    estimated_cost: "$0",
  },
  {
    rule_id: "AB-064",
    category: "documentation",
    icon: "📝",
    title: "Agent Registration Instructions",
    short_description: "Your site has instructions telling agents how to register and authenticate.",
    user_value: "Without clear registration instructions, agents can't sign up for your service or get API access.",
    wrong_example: "No registration instructions. Agents don't know how to get access.",
    right_example: "Clear instructions guide agents through registration and authentication step by step.",
    effort_hint: "moderate",
    estimated_cost: "$10-50",
  },
  {
    rule_id: "AB-140",
    category: "documentation",
    icon: "📖",
    title: "Auth.md documents agent auth flow",
    short_description: "Your auth.md file documents agent authentication with session-scoped tokens.",
    user_value: "Agents need documentation to discover and use auth flows. Auth.md should mention OAuth, session-scoped tokens, and agent-specific patterns.",
    wrong_example: "auth.md: 'Use API key in Authorization header.'",
    right_example: "auth.md: 'Agents must use OAuth2 with session-scoped tokens. See /.well-known/aauth.json for available scopes.'",
    effort_hint: "quick",
    estimated_cost: "$0",
  },
  {
    rule_id: "AB-144",
    category: "documentation",
    icon: "📖",
    title: "Auth.md documents credential vault pattern",
    short_description: "Your auth.md mentions credential vault, scoped tokens, or session rotation (optional).",
    user_value: "Credential vault documentation guides developers to use centralized credential management instead of embedding static keys in agents.",
    wrong_example: "auth.md: 'Use API key in header.'",
    right_example: "auth.md: 'Use credential vault with session-scoped tokens. Rotate keys regularly.'",
    effort_hint: "quick",
    estimated_cost: "$0",
  },
  {
    rule_id: "AB-147",
    category: "documentation",
    icon: "📋",
    title: "Parameter semantics",
    short_description: "Parameters have descriptions with constraints (min, max, required).",
    user_value: "Agents need to know what values are valid for each parameter — type alone is insufficient.",
    wrong_example: "parameters: [{ name: 'limit', in: 'query', schema: { type: 'integer' } }]",
    right_example: "parameters: [{ name: 'limit', in: 'query', description: 'Max results (1-100)', schema: { type: 'integer', minimum: 1, maximum: 100 } }]",
    effort_hint: "quick",
    estimated_cost: "$0",
    severity: "medium",
  },
  {
    rule_id: "AB-148",
    category: "documentation",
    icon: "💡",
    title: "Request/response examples",
    short_description: "OpenAPI operations include example requests and responses.",
    user_value: "Examples let agents construct valid requests without trial-and-error.",
    wrong_example: "responses: { '200': { description: 'OK' } }",
    right_example: "responses: { '200': { content: { 'application/json': { example: { id: 'ch_123', amount: 5000 } } } } }",
    effort_hint: "quick",
    estimated_cost: "$0",
    severity: "medium",
  },
  {
    rule_id: "AB-160",
    category: "documentation",
    icon: "🆘",
    title: "Support path declared",
    short_description: "A support contact or help URL is declared in agent-guide.",
    user_value: "Agents need to know where to direct users when something goes wrong.",
    wrong_example: "// no support info",
    right_example: 'agent-guide.json: { "support": { "email": "support@example.com", "url": "https://example.com/support" } }',
    effort_hint: "quick",
    estimated_cost: "$0",
    severity: "low",
  }
];
