import type { RuleDescription } from "./index";

export const infrastructureRules: RuleDescription[] = [
  {
    rule_id: "AB-045",
    category: "infrastructure",
    icon: "⚡",
    title: "Cache Headers",
    short_description: "Your site sends cache headers so agents and CDNs know how to cache your content.",
    user_value: "Proper caching means faster responses for agents and lower server costs for you.",
    wrong_example: "No cache headers. Every request hits your server, slowing agents down.",
    right_example: "Cache headers enable efficient caching, speeding up agent requests.",
    effort_hint: "quick",
    estimated_cost: "$0",
  },
  {
    rule_id: "AB-046",
    category: "infrastructure",
    icon: "🚫",
    title: "Structured 404 Errors",
    short_description: "Your site returns structured JSON for 404 errors instead of plain HTML.",
    user_value: "When agents hit a missing page, a structured error tells them what went wrong. An HTML 404 page is useless to machines.",
    wrong_example: "404 returns an HTML page. Agents can't parse the error.",
    right_example: "404 returns structured JSON with error details agents can understand.",
    effort_hint: "quick",
    estimated_cost: "$0",
  },
  {
    rule_id: "AB-047",
    category: "infrastructure",
    icon: "⏱️",
    title: "Rate Limit Headers",
    short_description: "Your site sends rate limit headers so agents know how many requests they can make.",
    user_value: "Rate limit headers let agents pace themselves and avoid getting blocked.",
    wrong_example: "No rate limit headers. Agents get blocked without warning.",
    right_example: "Rate limit headers tell agents exactly how many requests they have left.",
    effort_hint: "quick",
    estimated_cost: "$0",
  },
  {
    rule_id: "AB-073",
    category: "infrastructure",
    icon: "🔒",
    title: "HTTPS Redirect Enforced",
    short_description: "Your site automatically redirects HTTP requests to HTTPS so agents always use a secure connection.",
    user_value: "Agents expect secure connections. Without HTTPS redirect, agents may fail or warn users about insecure endpoints.",
    wrong_example: "HTTP requests return content without redirecting. Agents get insecure responses.",
    right_example: "HTTP requests redirect to HTTPS automatically. Agents always connect securely.",
    effort_hint: "quick",
    estimated_cost: "$0",
  },
  {
    rule_id: "AB-098",
    category: "infrastructure",
    icon: "🔒",
    title: "Content-Security-Policy header",
    short_description: "Your homepage returns a Content-Security-Policy header.",
    user_value: "CSP prevents XSS and data injection attacks by restricting resource sources. Critical for agent security when loading external scripts.",
    wrong_example: "No Content-Security-Policy header on responses.",
    right_example: "Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-inline'",
    effort_hint: "moderate",
    estimated_cost: "$0",
  },
  {
    rule_id: "AB-099",
    category: "infrastructure",
    icon: "🔒",
    title: "Referrer-Policy header",
    short_description: "Your homepage returns a Referrer-Policy header.",
    user_value: "Referrer-Policy controls how much referrer information is leaked, protecting user privacy when navigating between sites.",
    wrong_example: "No Referrer-Policy header on responses.",
    right_example: "Referrer-Policy: strict-origin-when-cross-origin",
    effort_hint: "quick",
    estimated_cost: "$0",
  }
];
