import type { RuleDescription } from "./index";

export const machineReadableRules: RuleDescription[] = [
  {
    rule_id: "AB-010",
    category: "machine_readable",
    icon: "💲",
    title: "Machine-Readable Pricing",
    short_description: "Your pricing information is available in a format agents can parse automatically.",
    user_value: "Agents need to compare prices programmatically. If pricing is only in HTML, they can't use it.",
    wrong_example: "Pricing only shown in HTML tables. Agents can't read or compare prices.",
    right_example: "Pricing is available as structured data that agents can read and compare.",
    effort_hint: "moderate",
    estimated_cost: "$10-50",
  },
  {
    rule_id: "AB-011",
    category: "machine_readable",
    icon: "⏱️",
    title: "Rate Limits Declared",
    short_description: "Your site declares its rate limits in a machine-readable format.",
    user_value: "Without rate limit info, agents may get blocked for making too many requests. With it, they pace themselves.",
    wrong_example: "No rate limit info. Agents get blocked unexpectedly.",
    right_example: "Rate limits are declared, so agents know exactly how fast they can make requests.",
    effort_hint: "moderate",
    estimated_cost: "$10-50",
  },
  {
    rule_id: "AB-012",
    category: "machine_readable",
    icon: "⚠️",
    title: "Structured Error Responses",
    short_description: "Your API returns errors in a consistent, machine-readable format.",
    user_value: "When agents get a structured error, they can understand what went wrong and retry correctly. Plain text errors are useless.",
    wrong_example: "Errors return plain text like 'Something went wrong'. Agents can't parse or respond to this.",
    right_example: "Errors return structured data with error code, message, and suggested action.",
    effort_hint: "moderate",
    estimated_cost: "$10-50",
  },
  {
    rule_id: "AB-020",
    category: "machine_readable",
    icon: "🛠️",
    title: "MCP Tools List",
    short_description: "Your MCP server responds to tool listing requests.",
    user_value: "Agents need to see what tools your MCP server offers before they can use any of them.",
    wrong_example: "MCP server doesn't respond to tool listing. Agents don't know what's available.",
    right_example: "MCP server lists all available tools with descriptions.",
    effort_hint: "moderate",
    estimated_cost: "$10-50",
  },
  {
    rule_id: "AB-021",
    category: "machine_readable",
    icon: "📞",
    title: "MCP Tool Calls",
    short_description: "Your MCP server responds when agents try to call a tool.",
    user_value: "Listing tools isn't enough — agents need to actually call them. If calls fail, your MCP server is useless.",
    wrong_example: "MCP server lists tools but doesn't respond when agents try to use them.",
    right_example: "MCP server processes tool calls and returns results.",
    effort_hint: "moderate",
    estimated_cost: "$10-50",
  },
  {
    rule_id: "AB-022",
    category: "machine_readable",
    icon: "📡",
    title: "MCP Streaming Support",
    short_description: "Your MCP server supports streaming connections for real-time communication.",
    user_value: "Streaming lets agents get results as they're produced, which is essential for long-running tasks.",
    wrong_example: "MCP server only supports one-shot requests. Long tasks time out.",
    right_example: "MCP server supports streaming, so agents get results in real time.",
    effort_hint: "complex",
    estimated_cost: "$100+",
  },
  {
    rule_id: "AB-109",
    category: "machine_readable",
    icon: "card",
    title: "Agent Card version 1.0.0+",
    short_description: "Agent Card JSON includes a version field >= 1.0.0.",
    user_value: "Agents use the version to determine compatibility and feature support when reading your agent card.",
    wrong_example: "{ \"name\": \"My API\" } — no version field.",
    right_example: "{ \"name\": \"My API\", \"version\": \"1.0.0\" } — semver version present.",
    effort_hint: "quick",
    estimated_cost: "$0",
  },
  {
    rule_id: "AB-163",
    category: "machine_readable",
    icon: "📋",
    title: "Skill.json (JSON-LD) availability",
    short_description: "Your site serves /skill.json as JSON-LD with @context, @type, name, and url/endpoints for machine-readable agent onboarding.",
    user_value: "AI agents can discover and understand your onboarding contract in a standardized JSON-LD format, enabling automated capability discovery.",
    wrong_example: "GET /skill.json → 404",
    right_example: '{"@context":"https://schema.org","@type":"SoftwareApplication","name":"MyAgent","url":"https://example.com/docs"}',
    effort_hint: "moderate",
    estimated_cost: "$0",
    severity: "low",
  },
  {
    rule_id: "AB-164",
    category: "machine_readable",
    icon: "❗",
    title: "Error catalog endpoint",
    short_description: "Your site serves a JSON error catalog at /api/meta/errors or /errors.json with error codes and descriptions.",
    user_value: "AI agents can programmatically look up error codes and meanings, enabling intelligent retry and error-handling decisions.",
    wrong_example: "GET /api/meta/errors → 404",
    right_example: '[{"code":"RATE_LIMITED","description":"Too many requests"},{"code":"INVALID_INPUT","description":"Validation failed"}]',
    effort_hint: "moderate",
    estimated_cost: "$0",
    severity: "low",
  }
];
