import type { RuleDescription } from "./index";

export const openapiRules: RuleDescription[] = [
  {
    rule_id: "AB-039",
    category: "openapi",
    icon: "📋",
    title: "API Spec at Standard Location",
    short_description: "Your API specification is published at the standard location agents expect.",
    user_value: "Agents look for API specs in standard places. If yours is elsewhere, they may never find it.",
    wrong_example: "API spec exists but at a non-standard URL. Agents don't know where to look.",
    right_example: "API spec is at the standard location, so agents find it immediately.",
    effort_hint: "quick",
    estimated_cost: "$0",
  },
  {
    rule_id: "AB-040",
    category: "openapi",
    icon: "🛤️",
    title: "API Paths Defined",
    short_description: "Your API specification lists all available paths and endpoints.",
    user_value: "Without defined paths, agents don't know what endpoints exist or how to call them.",
    wrong_example: "API spec is mostly empty. No paths defined.",
    right_example: "All API paths are defined with parameters and responses.",
    effort_hint: "complex",
    estimated_cost: "$100+",
  },
  {
    rule_id: "AB-041",
    category: "openapi",
    icon: "🌐",
    title: "API Paths Reachable",
    short_description: "All endpoints defined in your API spec actually work when agents call them.",
    user_value: "A spec that lists endpoints that don't work is worse than no spec — it wastes agents' time and breaks trust.",
    wrong_example: "API spec lists 10 endpoints, but 3 of them return errors.",
    right_example: "Every endpoint in the spec works as described.",
    effort_hint: "moderate",
    estimated_cost: "$10-50",
  },
  {
    rule_id: "AB-042",
    category: "openapi",
    icon: "🔍",
    title: "Response Matches Spec",
    short_description: "Your API responses match what your specification promises.",
    user_value: "If responses don't match the spec, agents get errors they can't predict. Consistency is key for trust.",
    wrong_example: "Spec says response has 'name' field, but actual response has 'username'. Agents break.",
    right_example: "Responses exactly match the specification.",
    effort_hint: "moderate",
    estimated_cost: "$10-50",
  },
  {
    rule_id: "AB-043",
    category: "openapi",
    icon: "🔢",
    title: "API Version Identified",
    short_description: "Your API specification clearly states which version it is.",
    user_value: "Version info lets agents handle changes gracefully. Without it, updates can break agent integrations silently.",
    wrong_example: "No version in the spec. Agents don't know if the API has changed.",
    right_example: "Version is clearly identified, so agents can adapt to changes.",
    effort_hint: "quick",
    estimated_cost: "$0",
  },
  {
    rule_id: "AB-044",
    category: "openapi",
    icon: "🏷️",
    title: "API Title",
    short_description: "Your API specification has a clear title that describes your service.",
    user_value: "A descriptive title helps agents understand what your API does at a glance.",
    wrong_example: "API spec has no title or a generic one like 'API'.",
    right_example: "A clear title like 'AgentBadge Passport API' tells agents exactly what it is.",
    effort_hint: "quick",
    estimated_cost: "$0",
  },
  {
    rule_id: "AB-076",
    category: "openapi",
    icon: "🛤️",
    title: "OpenAPI Paths Reachable",
    short_description: "At least half the paths declared in your OpenAPI spec return valid responses when probed.",
    user_value: "An OpenAPI spec with unreachable paths misleads agents. Reachable paths mean agents can actually use your API.",
    wrong_example: "OpenAPI declares 10 paths but only 2 respond. Agents waste calls on dead endpoints.",
    right_example: "Most declared paths respond correctly. Agents can rely on your spec to navigate your API.",
    effort_hint: "moderate",
    estimated_cost: "$10-50",
  },
  {
    rule_id: "AB-077",
    category: "openapi",
    icon: "📋",
    title: "OpenAPI Response Matches Spec",
    short_description: "Your API responses match the structure declared in your OpenAPI specification.",
    user_value: "When responses match the spec, agents can parse them reliably. Mismatches cause parsing errors and broken integrations.",
    wrong_example: "Spec says response has a 'data' array but the actual response returns an object. Agents crash trying to parse it.",
    right_example: "Responses match the spec exactly. Agents parse responses without surprises.",
    effort_hint: "moderate",
    estimated_cost: "$10-50",
  },
  {
    rule_id: "AB-078",
    category: "openapi",
    icon: "💳",
    title: "Payment Info in OpenAPI",
    short_description: "Your OpenAPI spec declares payment information for paid operations so agents know which endpoints cost money.",
    user_value: "Agents need to know which operations require payment before calling them. Declaring payment info prevents unexpected charges.",
    wrong_example: "Paid endpoints have no payment info in the spec. Agents call them and get surprise 402 errors.",
    right_example: "Paid operations clearly declare payment info. Agents know upfront which calls cost money.",
    effort_hint: "moderate",
    estimated_cost: "$10-50",
  }
];
