import type { RuleDescription } from "./index";

export const paymentsRules: RuleDescription[] = [
  {
    rule_id: "AB-030",
    category: "payments",
    icon: "💰",
    title: "Paid Endpoint Response",
    short_description: "When an agent tries to access a paid feature, your site responds with a clear payment request.",
    user_value: "This is how agents know a feature costs money and how to pay. Without it, agents hit a wall and move on.",
    wrong_example: "Paid endpoints return a generic error. Agents don't know payment is required.",
    right_example: "Paid endpoints clearly communicate the price and payment method.",
    effort_hint: "complex",
    estimated_cost: "$100+",
  },
  {
    rule_id: "AB-031",
    category: "payments",
    icon: "🔓",
    title: "Payment Challenge Decodable",
    short_description: "The payment request your site sends is properly formatted and can be decoded by agents.",
    user_value: "If agents can't decode the payment request, they can't pay — even if they want to.",
    wrong_example: "Payment request is malformed. Agents can't parse it to know what to pay.",
    right_example: "Payment request is well-formed and agents can decode it to complete payment.",
    effort_hint: "complex",
    estimated_cost: "$100+",
  },
  {
    rule_id: "AB-032",
    category: "payments",
    icon: "📋",
    title: "Payment Required Header",
    short_description: "Your payment responses include a header that tells agents payment is needed.",
    user_value: "This header is the universal signal for 'payment required'. Without it, agents don't know to look for payment details.",
    wrong_example: "No payment header. Agents don't realize they need to pay.",
    right_example: "Payment header clearly signals that payment is required.",
    effort_hint: "moderate",
    estimated_cost: "$10-50",
  },
  {
    rule_id: "AB-033",
    category: "payments",
    icon: "👤",
    title: "Payment Recipient",
    short_description: "Your payment requests specify who should receive the payment.",
    user_value: "Agents need to know where to send money. Without a recipient, payment is impossible.",
    wrong_example: "No recipient specified. Agents don't know who to pay.",
    right_example: "Payment recipient is clearly specified.",
    effort_hint: "moderate",
    estimated_cost: "$10-50",
  },
  {
    rule_id: "AB-034",
    category: "payments",
    icon: "💵",
    title: "Payment Amount",
    short_description: "Your payment requests specify how much the agent needs to pay.",
    user_value: "Without a clear price, agents can't decide whether a feature is worth paying for.",
    wrong_example: "No amount specified. Agents don't know how much the service costs.",
    right_example: "Price is clearly stated in the payment request.",
    effort_hint: "moderate",
    estimated_cost: "$10-50",
  },
  {
    rule_id: "AB-035",
    category: "payments",
    icon: "📄",
    title: "Payment Discovery File",
    short_description: "Your site publishes a file that describes all payment options in one place.",
    user_value: "A payment discovery file lets agents understand your pricing model before making any requests.",
    wrong_example: "No payment discovery file. Agents have to trigger paid endpoints to learn pricing.",
    right_example: "A published file describes all payment options upfront.",
    effort_hint: "moderate",
    estimated_cost: "$10-50",
  },
  {
    rule_id: "AB-038",
    category: "payments",
    icon: "🏦",
    title: "Payment Facilitator",
    short_description: "Your payment requests specify a facilitator that can process the payment.",
    user_value: "A facilitator handles the payment mechanics. Without one, agents can't complete transactions.",
    wrong_example: "No facilitator specified. Agents don't know how to process the payment.",
    right_example: "A facilitator is specified, so agents know how to complete payment.",
    effort_hint: "complex",
    estimated_cost: "$100+",
  },
  {
    rule_id: "AB-070",
    category: "payments",
    icon: "⚡",
    title: "Lightning Payment Support",
    short_description: "Your site supports Lightning Network payments for instant, low-cost transactions.",
    user_value: "Lightning payments are instant and cost fractions of a cent — ideal for micro-transactions between agents.",
    wrong_example: "Only traditional payment methods. Slow and expensive for small agent transactions.",
    right_example: "Lightning payments enable instant micro-transactions between agents.",
    effort_hint: "complex",
    estimated_cost: "$100+",
  },
  {
    rule_id: "AB-071",
    category: "payments",
    icon: "🎫",
    title: "Lightning Payment Details",
    short_description: "Your Lightning payment responses include all required details for agents to pay.",
    user_value: "Lightning payments require specific details. Missing any of them means the payment can't be completed.",
    wrong_example: "Lightning payment response is incomplete. Agents can't complete the transaction.",
    right_example: "All required Lightning payment details are included.",
    effort_hint: "complex",
    estimated_cost: "$100+",
  },
  {
    rule_id: "AB-088",
    category: "payments",
    icon: "💳",
    title: "MPP (Machine Payments Protocol) Support",
    short_description: "Checks for /.well-known/mpp.json declaring Machine Payments Protocol support.",
    user_value: "Agents can discover MPP-compatible endpoints and initiate machine-to-machine payments without manual configuration.",
    wrong_example: "No /.well-known/mpp.json endpoint published — agents cannot determine MPP support.",
    right_example: "GET /.well-known/mpp.json returns 200 with { \"protocol\": \"mpp\", \"version\": \"1.0\" }.",
    effort_hint: "quick",
    estimated_cost: "$0-10",
  },
  {
    rule_id: "AB-093",
    category: "payments",
    icon: "💳",
    title: "SPT (Stripe Payment Terms) Support",
    short_description: "Checks for /.well-known/spt.json declaring Stripe Payment Terms support.",
    user_value: "Agents can discover Stripe-based payment endpoints and use Stripe for automated transactions.",
    wrong_example: "No /.well-known/spt.json endpoint published — agents cannot determine SPT support.",
    right_example: "GET /.well-known/spt.json returns 200 with { \"stripe_publishable_key\": \"pk_live_...\" }.",
    effort_hint: "quick",
    estimated_cost: "$0-10",
  }
];
