import type { RuleDescription } from "./index";

export const seoAeoRules: RuleDescription[] = [
  {
    rule_id: "AB-104",
    category: "seo_aeo",
    icon: "🔎",
    title: "Blog Article OpenGraph Type",
    short_description: "Blog and article pages declare og:type=article in their OpenGraph meta tags.",
    user_value: "Search engines and social platforms use og:type to correctly categorize and display article content.",
    wrong_example: "Blog post page has no og:type meta tag or sets og:type to 'website' instead of 'article'.",
    right_example: "<meta property=\"og:type\" content=\"article\"> in the HTML head of /blog/my-post.",
    effort_hint: "quick",
    estimated_cost: "$0-10",
  },
  {
    rule_id: "AB-105",
    category: "seo_aeo",
    icon: "🔎",
    title: "Article Author and Date Meta Tags",
    short_description: "Article pages include article:author, article:published_time, and article:modified_time meta tags.",
    user_value: "AI answer engines and search crawlers use author and date metadata to assess content freshness and credibility.",
    wrong_example: "Blog post has no article:author or article:published_time meta tags.",
    right_example: "<meta property=\"article:author\" content=\"Jane Doe\"> and <meta property=\"article:published_time\" content=\"2026-08-01T00:00:00Z\">.",
    effort_hint: "quick",
    estimated_cost: "$0-10",
  },
  {
    rule_id: "AB-106",
    category: "seo_aeo",
    icon: "🔎",
    title: "AEO Short-Answer Summary Block",
    short_description: "Article pages include a short-answer summary block (2-3 sentences) at the top for AI answer engines.",
    user_value: "AI answer engines like Perplexity and Google SGE extract concise answers from summary blocks, increasing content visibility.",
    wrong_example: "Article starts with a long introduction paragraph without a concise summary.",
    right_example: "Article begins with a <section class=\"summary\"> containing 2-3 sentences answering the page's core question.",
    effort_hint: "moderate",
    estimated_cost: "$0-10",
  },
  {
    rule_id: "AB-107",
    category: "seo_aeo",
    icon: "🔎",
    title: "Semantic Definition Lists in Guides",
    short_description: "Guide pages use <dl> definition lists for term/definition pairs instead of plain paragraphs.",
    user_value: "Definition lists provide structured semantic markup that AI agents can parse for glossary-style content.",
    wrong_example: "Guide page uses <p><strong>Term:</strong> Definition</p> instead of <dl><dt>Term</dt><dd>Definition</dd></dl>.",
    right_example: "Guide page includes <dl><dt>API</dt><dd>Application Programming Interface</dd></dl> for key terms.",
    effort_hint: "moderate",
    estimated_cost: "$0-10",
  },
  {
    rule_id: "AB-108",
    category: "seo_aeo",
    icon: "🔎",
    title: "OG Image Alt Text Brand Consistency",
    short_description: "og:image:alt text is present and includes the site's brand name for consistent social sharing.",
    user_value: "Branded og:image:alt text improves accessibility and brand recognition when content is shared on social platforms.",
    wrong_example: "<meta property=\"og:image:alt\" content=\"image\"> — generic alt text without brand name.",
    right_example: "<meta property=\"og:image:alt\" content=\"AgentBadge — Agent Readiness Diagram\"> includes brand name.",
    effort_hint: "quick",
    estimated_cost: "$0-10",
  },
  {
    rule_id: "AB-100",
    category: "seo_aeo",
    icon: "📝",
    title: "Service page content depth",
    short_description: "Service pages have at least 300 words of meaningful content.",
    user_value: "Content depth signals expertise to both search engines and AI agents. Thin pages rank poorly and provide little context for AI comprehension.",
    wrong_example: "Service page with 50 words: 'We offer API services. Contact us for more info.'",
    right_example: "Service page with 300+ words covering features, use cases, pricing context, and technical details.",
    effort_hint: "moderate",
    estimated_cost: "$0",
  },
  {
    rule_id: "AB-101",
    category: "seo_aeo",
    icon: "📝",
    title: "Breadcrumb navigation on service pages",
    short_description: "Service pages have breadcrumb navigation (JSON-LD BreadcrumbList or HTML .breadcrumb class).",
    user_value: "Breadcrumbs help users and search engines understand page hierarchy. JSON-LD breadcrumbs enable rich snippets in search results.",
    wrong_example: "Service page with no breadcrumb navigation — users can't navigate back to category pages.",
    right_example: "BreadcrumbList JSON-LD schema or HTML nav with .breadcrumb class showing Home > Services > API.",
    effort_hint: "quick",
    estimated_cost: "$0",
  }
];
