import type { RuleDescription } from "./index";

export const seoAeoRules: RuleDescription[] = [
  {
    rule_id: "AB-104",
    category: "seo_aeo",
    icon: "🔎",
    title: "Blog Article OpenGraph Type",
    short_description: "Blog and article pages declare og:type=article in their OpenGraph meta tags.",
    user_value: "Search engines and social platforms use og:type to correctly categorize and display article content.",
    wrong_example: "Blog post page has no og:type meta tag or sets og:type to 'website' instead of 'article'.",
    right_example: "<meta property=\"og:type\" content=\"article\"> in the HTML head of /blog/my-post.",
    effort_hint: "quick",
    estimated_cost: "$0-10",
  },
  {
    rule_id: "AB-105",
    category: "seo_aeo",
    icon: "🔎",
    title: "Article Author and Date Meta Tags",
    short_description: "Article pages include article:author, article:published_time, and article:modified_time meta tags.",
    user_value: "AI answer engines and search crawlers use author and date metadata to assess content freshness and credibility.",
    wrong_example: "Blog post has no article:author or article:published_time meta tags.",
    right_example: "<meta property=\"article:author\" content=\"Jane Doe\"> and <meta property=\"article:published_time\" content=\"2026-08-01T00:00:00Z\">.",
    effort_hint: "quick",
    estimated_cost: "$0-10",
  },
  {
    rule_id: "AB-106",
    category: "seo_aeo",
    icon: "🔎",
    title: "AEO Short-Answer Summary Block",
    short_description: "Article pages include a short-answer summary block (2-3 sentences) at the top for AI answer engines.",
    user_value: "AI answer engines like Perplexity and Google SGE extract concise answers from summary blocks, increasing content visibility.",
    wrong_example: "Article starts with a long introduction paragraph without a concise summary.",
    right_example: "Article begins with a <section class=\"summary\"> containing 2-3 sentences answering the page's core question.",
    effort_hint: "moderate",
    estimated_cost: "$0-10",
  },
  {
    rule_id: "AB-107",
    category: "seo_aeo",
    icon: "🔎",
    title: "Semantic Definition Lists in Guides",
    short_description: "Guide pages use <dl> definition lists for term/definition pairs instead of plain paragraphs.",
    user_value: "Definition lists provide structured semantic markup that AI agents can parse for glossary-style content.",
    wrong_example: "Guide page uses <p><strong>Term:</strong> Definition</p> instead of <dl><dt>Term</dt><dd>Definition</dd></dl>.",
    right_example: "Guide page includes <dl><dt>API</dt><dd>Application Programming Interface</dd></dl> for key terms.",
    effort_hint: "moderate",
    estimated_cost: "$0-10",
  },
  {
    rule_id: "AB-108",
    category: "seo_aeo",
    icon: "🔎",
    title: "OG Image Alt Text Brand Consistency",
    short_description: "og:image:alt text is present and includes the site's brand name for consistent social sharing.",
    user_value: "Branded og:image:alt text improves accessibility and brand recognition when content is shared on social platforms.",
    wrong_example: "<meta property=\"og:image:alt\" content=\"image\"> — generic alt text without brand name.",
    right_example: "<meta property=\"og:image:alt\" content=\"AgentBadge — Agent Readiness Diagram\"> includes brand name.",
    effort_hint: "quick",
    estimated_cost: "$0-10",
  },
  {
    rule_id: "AB-100",
    category: "seo_aeo",
    icon: "📝",
    title: "Service page content depth",
    short_description: "Service pages have at least 300 words of meaningful content.",
    user_value: "Content depth signals expertise to both search engines and AI agents. Thin pages rank poorly and provide little context for AI comprehension.",
    wrong_example: "Service page with 50 words: 'We offer API services. Contact us for more info.'",
    right_example: "Service page with 300+ words covering features, use cases, pricing context, and technical details.",
    effort_hint: "moderate",
    estimated_cost: "$0",
  },
  {
    rule_id: "AB-101",
    category: "seo_aeo",
    icon: "📝",
    title: "Breadcrumb navigation on service pages",
    short_description: "Service pages have breadcrumb navigation (JSON-LD BreadcrumbList or HTML .breadcrumb class).",
    user_value: "Breadcrumbs help users and search engines understand page hierarchy. JSON-LD breadcrumbs enable rich snippets in search results.",
    wrong_example: "Service page with no breadcrumb navigation — users can't navigate back to category pages.",
    right_example: "BreadcrumbList JSON-LD schema or HTML nav with .breadcrumb class showing Home > Services > API.",
    effort_hint: "quick",
    estimated_cost: "$0",
  },
  {
    rule_id: "AB-183",
    category: "seo_aeo",
    icon: "❓",
    title: "Answer-first extractability",
    short_description: "Question-shaped headings are followed by self-contained answer blocks AI systems can quote.",
    user_value: "AI answer engines lift passages verbatim. A question heading followed by a tight 80-200 word answer is the format they cite.",
    wrong_example: "H2 'How does pricing work?' followed by five paragraphs of context before the actual answer.",
    right_example: "H2 question + first paragraph that fully answers it in 80-200 words, no pronoun references to earlier sections.",
    effort_hint: "moderate",
    estimated_cost: "$0",
  },
  {
    rule_id: "AB-184",
    category: "seo_aeo",
    icon: "📊",
    title: "Evidence density for citability",
    short_description: "Pages contain citable evidence: sourced numbers, dated claims, fact tables, attributed quotations.",
    user_value: "GEO research shows statistics and quotations drive AI citations (+33-41% visibility). Models cannot invent verifiable facts.",
    wrong_example: "Marketing prose only: 'the industry-leading platform trusted by thousands' with zero sourced data.",
    right_example: "'According to our 2026 benchmark, median scan time is 4.2s' + a comparison table + attributed expert quote.",
    effort_hint: "moderate",
    estimated_cost: "$0",
  },
  {
    rule_id: "AB-185",
    category: "seo_aeo",
    icon: "🏷️",
    title: "Entity clarity and canonical naming",
    short_description: "The page states what the entity is in one canonical line, names it consistently, and links About/schema signals.",
    user_value: "Models must unambiguously identify who you are before citing you. Consistent naming across title, og:site_name and JSON-LD builds entity confidence.",
    wrong_example: "Brand spelled three ways, no 'X is a ...' description, no About page link.",
    right_example: "'AgentBadge is an agent-readiness scanner for API providers' + identical name in title/og/JSON-LD + /about link.",
    effort_hint: "quick",
    estimated_cost: "$0",
  },
  {
    rule_id: "AB-186",
    category: "seo_aeo",
    icon: "🖥️",
    title: "Server-rendered primary content",
    short_description: "Primary content is present in the initial HTML without executing JavaScript.",
    user_value: "AI crawlers (GPTBot, PerplexityBot, ClaudeBot) largely do not run JS. A CSR-only shell is invisible to them.",
    wrong_example: "<div id=\"root\"></div> + <script src=\"bundle.js\"> — empty HTML until hydration.",
    right_example: "Headings and paragraphs rendered server-side; JS only enhances interactivity.",
    effort_hint: "project",
    estimated_cost: "$0",
  },
  {
    rule_id: "AB-187",
    category: "seo_aeo",
    icon: "🚫",
    title: "Anti-citation disqualifiers",
    short_description: "Content is free of overlays covering it, funnel-grade CTA density, and missing author/date on articles.",
    user_value: "Models deprioritize pages that read like gated funnels: cookie walls over content, CTA-saturated copy, anonymous undated articles.",
    wrong_example: "Full-viewport modal over the article + every paragraph ends with 'Sign up now' + no author or date.",
    right_example: "Content unobstructed; named author and publish date; CTAs confined to header/footer.",
    effort_hint: "moderate",
    estimated_cost: "$0",
  }
];
