import type { RuleDescription } from "./index";

export const webmcpRules: RuleDescription[] = [
  {
    rule_id: "AB-050",
    category: "webmcp",
    icon: "🌐",
    title: "WebMCP Manifest",
    short_description: "Your site has a WebMCP manifest that enables browser-based agent interactions.",
    user_value: "WebMCP lets agents interact with your site directly through the browser, opening up new interaction patterns.",
    wrong_example: "No WebMCP manifest. Browser-based agents can't interact with your site.",
    right_example: "A WebMCP manifest enables rich browser-based agent interactions.",
    effort_hint: "complex",
    estimated_cost: "$100+",
  },
  {
    rule_id: "AB-051",
    category: "webmcp",
    icon: "📝",
    title: "WebMCP Form Annotations",
    short_description: "Your forms are annotated so WebMCP agents can fill them automatically.",
    user_value: "Annotations let agents understand and fill your forms, enabling automated interactions like registration and checkout.",
    wrong_example: "Forms have no annotations. Agents can't understand what fields mean or how to fill them.",
    right_example: "Forms are annotated, so agents can fill them automatically and correctly.",
    effort_hint: "moderate",
    estimated_cost: "$10-50",
  },
  {
    rule_id: "AB-069",
    category: "webmcp",
    icon: "🖥️",
    title: "WebMCP Browser Tools",
    short_description: "Your site exposes browser-side tools that agents can call through WebMCP.",
    user_value: "Browser-side tools let agents perform actions that require a browser context, like rendering or interaction.",
    wrong_example: "No browser-side tools. Agents are limited to server-side API calls.",
    right_example: "Browser-side tools enable agents to perform rich interactions.",
    effort_hint: "complex",
    estimated_cost: "$100+",
  },
  {
    rule_id: "AB-115",
    category: "webmcp",
    icon: "🌐",
    title: "MCP namespace-based tool isolation",
    short_description: "Your MCP server exposes tools with namespace prefixes for multi-registry support.",
    user_value: "Namespace prefixes (e.g., 'passport.request') enable multi-registry architectures where tools from different registries coexist without name collisions.",
    wrong_example: "MCP tools are named 'request', 'submit', 'check' with no namespace prefix.",
    right_example: "MCP tools are named 'passport.request', 'wallet.submit', 'health.check' with clear namespace prefixes.",
    effort_hint: "moderate",
    estimated_cost: "$0",
  },
  {
    rule_id: "AB-116",
    category: "webmcp",
    icon: "🌐",
    title: "Well-known MCP descriptor",
    short_description: "Your site publishes an MCP server descriptor at /.well-known/mcp.json.",
    user_value: "A well-known MCP descriptor lets agents discover your MCP server's transport, capabilities, and tool registry without manual configuration.",
    wrong_example: "No /.well-known/mcp.json endpoint. Agents must guess your MCP server's location and capabilities.",
    right_example: "/.well-known/mcp.json returns JSON with server info, transport type, and tool registry.",
    effort_hint: "quick",
    estimated_cost: "$0",
  },
  {
    rule_id: "AB-102",
    category: "webmcp",
    icon: "🌐",
    title: "MCP tools and REST endpoints parity",
    short_description: "At least 50% of your REST API endpoints have corresponding MCP tools.",
    user_value: "MCP-to-REST parity ensures agents can interact with your API through MCP without missing critical functionality. Low parity means agents must fall back to REST, defeating the purpose of MCP.",
    wrong_example: "OpenAPI spec has 20 endpoints but MCP server exposes only 3 tools (15% parity).",
    right_example: "OpenAPI spec has 20 endpoints and MCP server exposes 12 tools (60% parity).",
    effort_hint: "complex",
    estimated_cost: "$0",
  },
  {
    rule_id: "AB-103",
    category: "webmcp",
    icon: "🌐",
    title: "check_compliance MCP tool available",
    short_description: "Your MCP server exposes a 'check_compliance' tool for self-assessment.",
    user_value: "A check_compliance tool lets agents verify their own readiness against your API requirements without external scanning. This enables autonomous compliance checking.",
    wrong_example: "MCP server exposes tools for data operations but no compliance or self-check tool.",
    right_example: "MCP server exposes a 'check_compliance' tool that returns readiness status and missing requirements.",
    effort_hint: "moderate",
    estimated_cost: "$0",
  }
];
