import type { Category } from "./shared.schema";

export interface RuleDescription {
  rule_id: string;
  category: Category;
  icon: string;
  title: string;
  short_description: string;
  user_value: string;
  wrong_example: string;
  right_example: string;
  effort_hint: "quick" | "moderate" | "complex";
  estimated_cost: string;
}

export interface CategoryDescription {
  icon: string;
  title: string;
  description: string;
}

export const CATEGORY_DESCRIPTIONS: Record<Category, CategoryDescription> = {
  discovery: {
    icon: "🔍",
    title: "Discovery",
    description: "Can AI agents find your site and understand what it offers?",
  },
  documentation: {
    icon: "📖",
    title: "Documentation",
    description: "Is your API documented in formats that AI agents can read?",
  },
  actionability: {
    icon: "⚡",
    title: "Actionability",
    description: "Can agents actually call your API with the right authentication?",
  },
  machine_readable: {
    icon: "🤖",
    title: "Machine-Readable",
    description: "Is your site's data structured for AI consumption?",
  },
  verification: {
    icon: "✅",
    title: "Verification",
    description: "Can agents verify you are who you say you are?",
  },
  content_negotiation: {
    icon: "🔄",
    title: "Content Negotiation",
    description: "Does your site serve the right format to AI agents?",
  },
  payments: {
    icon: "💰",
    title: "Payments",
    description: "Can agents pay for your services programmatically?",
  },
  bazaar: {
    icon: "🏪",
    title: "Bazaar",
    description: "Is your agent listed in the decentralized marketplace?",
  },
  openapi: {
    icon: "📋",
    title: "OpenAPI",
    description: "Is your API specification complete and reachable?",
  },
  skills: {
    icon: "🎯",
    title: "Skills",
    description: "Can agents discover and use your specialized skills?",
  },
  agents_txt: {
    icon: "📜",
    title: "Agents.txt",
    description: "Do you have instructions specifically for AI agents?",
  },
  webmcp: {
    icon: "🌐",
    title: "WebMCP",
    description: "Can browsers interact with your agent via MCP?",
  },
  identity: {
    icon: "🪪",
    title: "Identity",
    description: "Can agents verify your on-chain identity?",
  },
  bot_auth: {
    icon: "🔐",
    title: "Bot Authentication",
    description: "Can you prove which AI bot is making the request?",
  },
  infrastructure: {
    icon: "🏗️",
    title: "Infrastructure",
    description: "Are your caching, errors, and rate limits agent-ready?",
  },
};

export const RULE_DESCRIPTIONS: RuleDescription[] = [
  // ─── Discovery (8 rules) ─────────────────────────────
  {
    rule_id: "AB-001",
    category: "discovery",
    icon: "🔍",
    title: "Robots.txt File",
    short_description: "Your site has a robots.txt file that tells crawlers and AI agents what they can access.",
    user_value: "Without this file, AI agents don't know which parts of your site they're allowed to read, and may skip your content entirely.",
    wrong_example: "No robots.txt file found. Agents assume nothing is allowed.",
    right_example: "A clear robots.txt welcomes AI agents to explore your content.",
    effort_hint: "quick",
    estimated_cost: "$0",
  },
  {
    rule_id: "AB-002",
    category: "discovery",
    icon: "🗺️",
    title: "Sitemap File",
    short_description: "Your site has a sitemap listing all important pages for agents to discover.",
    user_value: "A sitemap ensures AI agents find every page on your site, not just the ones they stumble upon.",
    wrong_example: "No sitemap. Agents only find pages through external links.",
    right_example: "A complete sitemap lists all 20+ pages for easy discovery.",
    effort_hint: "quick",
    estimated_cost: "$0",
  },
  {
    rule_id: "AB-003",
    category: "discovery",
    icon: "🧭",
    title: "Agent Guide",
    short_description: "Your site has a dedicated guide that tells AI agents what you offer and how to interact.",
    user_value: "An agent guide is your front door for AI visitors. Without it, agents don't know what your site does.",
    wrong_example: "No agent guide. AI agents have to guess what your site is about.",
    right_example: "A clear guide explains your services, capabilities, and how to interact.",
    effort_hint: "moderate",
    estimated_cost: "$10-50",
  },
  {
    rule_id: "AB-014",
    category: "discovery",
    icon: "📄",
    title: "LLMs.txt File",
    short_description: "Your site has an llms.txt file that provides a plain-text overview for large language models.",
    user_value: "LLMs read this file to quickly understand your site without parsing HTML. It's like a README for AI.",
    wrong_example: "No llms.txt. AI models have to parse your HTML and may miss key information.",
    right_example: "A concise llms.txt gives AI models everything they need in plain text.",
    effort_hint: "quick",
    estimated_cost: "$0",
  },
  {
    rule_id: "AB-061",
    category: "discovery",
    icon: "🔗",
    title: "Link Relationships",
    short_description: "Your homepage includes link headers that connect related resources together.",
    user_value: "Link headers help agents navigate your site by following relationships between pages, like a map.",
    wrong_example: "No link relationships. Agents can't discover related pages automatically.",
    right_example: "Links connect your guide, API docs, and sitemap so agents can explore everything.",
    effort_hint: "moderate",
    estimated_cost: "$10-50",
  },
  {
    rule_id: "AB-062",
    category: "discovery",
    icon: "📚",
    title: "API Catalog",
    short_description: "Your site publishes a catalog of all available APIs in a standard location.",
    user_value: "An API catalog lets agents discover everything they can do with your site in one place.",
    wrong_example: "No API catalog. Agents have to guess or search for available endpoints.",
    right_example: "A catalog lists all APIs with descriptions, so agents know exactly what's available.",
    effort_hint: "moderate",
    estimated_cost: "$10-50",
  },
  {
    rule_id: "AB-066",
    category: "discovery",
    icon: "🏷️",
    title: "Content Signals",
    short_description: "Your robots.txt declares preferences about how AI can use your content.",
    user_value: "Content signals let you control whether AI can train on, search, or use your content as input — protecting your rights.",
    wrong_example: "No content signals. AI systems assume default permissions, which may not match your wishes.",
    right_example: "Clear signals tell AI systems exactly what they can and can't do with your content.",
    effort_hint: "quick",
    estimated_cost: "$0",
  },
  {
    rule_id: "AB-068",
    category: "discovery",
    icon: "🌐",
    title: "DNS Agent Discovery",
    short_description: "Your domain has DNS records that help agents discover your services automatically.",
    user_value: "DNS-based discovery means agents can find you without prior knowledge of your URL — like a phone book for AI.",
    wrong_example: "No DNS discovery records. Agents can only find you if they already know your URL.",
    right_example: "DNS records announce your agent services to the world.",
    effort_hint: "moderate",
    estimated_cost: "$10-50",
  },

  // ─── Documentation (11 rules) ────────────────────────
  {
    rule_id: "AB-004",
    category: "documentation",
    icon: "📋",
    title: "API Specification",
    short_description: "Your site has a machine-readable API specification that agents can parse.",
    user_value: "An API spec is how agents understand what your API does, what parameters it accepts, and what it returns.",
    wrong_example: "No API specification. Agents can't use your API without guessing.",
    right_example: "A complete API specification tells agents exactly how to use your service.",
    effort_hint: "complex",
    estimated_cost: "$100+",
  },
  {
    rule_id: "AB-005",
    category: "documentation",
    icon: "🧪",
    title: "Agent Guide Schema Validation",
    short_description: "Your agent guide follows the expected format with all required fields.",
    user_value: "A valid agent guide means agents can reliably parse it. An invalid guide is worse than none — it causes errors.",
    wrong_example: "Agent guide exists but is missing required fields or has wrong format.",
    right_example: "Agent guide passes validation with all required fields properly filled.",
    effort_hint: "moderate",
    estimated_cost: "$10-50",
  },
  {
    rule_id: "AB-006",
    category: "documentation",
    icon: "🔌",
    title: "MCP Server Descriptor",
    short_description: "Your site advertises its MCP server so agents can discover and connect to it.",
    user_value: "MCP is the standard way agents interact with services. Without a descriptor, agents don't know you support it.",
    wrong_example: "No MCP descriptor. Agents don't know your site has an MCP server.",
    right_example: "MCP descriptor is discoverable, so agents can connect and use your tools.",
    effort_hint: "moderate",
    estimated_cost: "$10-50",
  },
  {
    rule_id: "AB-024",
    category: "documentation",
    icon: "📑",
    title: "Detailed LLMs File",
    short_description: "Your site has an extended llms-full.txt with comprehensive information for AI models.",
    user_value: "While llms.txt is a summary, llms-full.txt gives AI models the complete picture of your service.",
    wrong_example: "Only a basic llms.txt. AI models get a summary but miss important details.",
    right_example: "A comprehensive llms-full.txt gives AI models everything they need to understand your service.",
    effort_hint: "moderate",
    estimated_cost: "$10-50",
  },
  {
    rule_id: "AB-025",
    category: "documentation",
    icon: "📌",
    title: "LLMs File Linked from HTML",
    short_description: "Your homepage links to your llms.txt file so AI models can find it.",
    user_value: "Even if you have llms.txt, agents won't find it unless it's linked from your pages.",
    wrong_example: "llms.txt exists but isn't linked from any page. AI models may never find it.",
    right_example: "llms.txt is linked from your homepage, making it easy for AI to discover.",
    effort_hint: "quick",
    estimated_cost: "$0",
  },
  {
    rule_id: "AB-049",
    category: "documentation",
    icon: "📡",
    title: "RSS or Atom Feed",
    short_description: "Your site has an RSS or Atom feed for agents to subscribe to updates.",
    user_value: "Feeds let agents monitor your site for changes without crawling it repeatedly.",
    wrong_example: "No RSS feed. Agents have to re-crawl your site to check for updates.",
    right_example: "An RSS feed lets agents subscribe and get notified of new content automatically.",
    effort_hint: "moderate",
    estimated_cost: "$10-50",
  },
  {
    rule_id: "AB-052",
    category: "documentation",
    icon: "🖼️",
    title: "Social Preview Image",
    short_description: "Your site has a social preview image that appears when shared on social media or in AI responses.",
    user_value: "A preview image makes your site look professional when shared or cited by AI, increasing click-through rates.",
    wrong_example: "No social preview image. Links to your site look plain and get fewer clicks.",
    right_example: "A branded preview image appears whenever your site is shared or cited.",
    effort_hint: "quick",
    estimated_cost: "$0",
  },
  {
    rule_id: "AB-053",
    category: "documentation",
    icon: "⭐",
    title: "SVG Favicon",
    short_description: "Your site has a scalable SVG favicon that looks crisp at any size.",
    user_value: "SVG favicons look sharp on all devices and can be used by AI systems to represent your brand.",
    wrong_example: "Only a raster favicon. Looks blurry when scaled up.",
    right_example: "An SVG favicon stays crisp at any resolution.",
    effort_hint: "quick",
    estimated_cost: "$0",
  },
  {
    rule_id: "AB-054",
    category: "documentation",
    icon: "🔗",
    title: "Canonical URL",
    short_description: "Your pages have canonical URLs that tell agents which version is the official one.",
    user_value: "Canonical URLs prevent duplicate content issues and ensure agents reference the right page.",
    wrong_example: "No canonical URLs. Agents may index duplicate versions of your pages.",
    right_example: "Each page has a canonical URL, so agents know which version is official.",
    effort_hint: "quick",
    estimated_cost: "$0",
  },
  {
    rule_id: "AB-055",
    category: "documentation",
    icon: "📰",
    title: "RSS Feed Linked from HTML",
    short_description: "Your homepage links to your RSS feed so agents can discover it.",
    user_value: "Even if you have an RSS feed, agents won't find it unless it's linked from your pages.",
    wrong_example: "RSS feed exists but isn't linked. Agents may not discover it.",
    right_example: "RSS feed is linked from your homepage for easy discovery.",
    effort_hint: "quick",
    estimated_cost: "$0",
  },
  {
    rule_id: "AB-064",
    category: "documentation",
    icon: "📝",
    title: "Agent Registration Instructions",
    short_description: "Your site has instructions telling agents how to register and authenticate.",
    user_value: "Without clear registration instructions, agents can't sign up for your service or get API access.",
    wrong_example: "No registration instructions. Agents don't know how to get access.",
    right_example: "Clear instructions guide agents through registration and authentication step by step.",
    effort_hint: "moderate",
    estimated_cost: "$10-50",
  },

  // ─── Actionability (3 rules) ─────────────────────────
  {
    rule_id: "AB-007",
    category: "actionability",
    icon: "🔄",
    title: "Guide and API Consistency",
    short_description: "Your agent guide and your API specification describe the same endpoints.",
    user_value: "If your guide says one thing but your API does another, agents will fail and avoid your service.",
    wrong_example: "Guide mentions endpoints that don't exist in the API spec, or vice versa.",
    right_example: "Guide and API spec are perfectly aligned — what agents read is what they get.",
    effort_hint: "moderate",
    estimated_cost: "$10-50",
  },
  {
    rule_id: "AB-008",
    category: "actionability",
    icon: "🔑",
    title: "Authentication Declared",
    short_description: "Your site declares its authentication method in a machine-readable way.",
    user_value: "Agents need to know how to authenticate before they can use your API. Without this, they're locked out.",
    wrong_example: "No machine-readable auth info. Agents don't know if they need API keys, OAuth, or something else.",
    right_example: "Authentication method is clearly declared, so agents know exactly how to get access.",
    effort_hint: "moderate",
    estimated_cost: "$10-50",
  },
  {
    rule_id: "AB-009",
    category: "actionability",
    icon: "🧩",
    title: "Capability Coverage",
    short_description: "Your agent guide covers all the capabilities your service offers.",
    user_value: "If your guide only mentions half your features, agents will only use half your service.",
    wrong_example: "Guide only covers 3 out of 10 available features.",
    right_example: "Guide covers all capabilities, so agents can use everything you offer.",
    effort_hint: "moderate",
    estimated_cost: "$10-50",
  },

  // ─── Machine-Readable (6 rules) ──────────────────────
  {
    rule_id: "AB-010",
    category: "machine_readable",
    icon: "💲",
    title: "Machine-Readable Pricing",
    short_description: "Your pricing information is available in a format agents can parse automatically.",
    user_value: "Agents need to compare prices programmatically. If pricing is only in HTML, they can't use it.",
    wrong_example: "Pricing only shown in HTML tables. Agents can't read or compare prices.",
    right_example: "Pricing is available as structured data that agents can read and compare.",
    effort_hint: "moderate",
    estimated_cost: "$10-50",
  },
  {
    rule_id: "AB-011",
    category: "machine_readable",
    icon: "⏱️",
    title: "Rate Limits Declared",
    short_description: "Your site declares its rate limits in a machine-readable format.",
    user_value: "Without rate limit info, agents may get blocked for making too many requests. With it, they pace themselves.",
    wrong_example: "No rate limit info. Agents get blocked unexpectedly.",
    right_example: "Rate limits are declared, so agents know exactly how fast they can make requests.",
    effort_hint: "moderate",
    estimated_cost: "$10-50",
  },
  {
    rule_id: "AB-012",
    category: "machine_readable",
    icon: "⚠️",
    title: "Structured Error Responses",
    short_description: "Your API returns errors in a consistent, machine-readable format.",
    user_value: "When agents get a structured error, they can understand what went wrong and retry correctly. Plain text errors are useless.",
    wrong_example: "Errors return plain text like 'Something went wrong'. Agents can't parse or respond to this.",
    right_example: "Errors return structured data with error code, message, and suggested action.",
    effort_hint: "moderate",
    estimated_cost: "$10-50",
  },
  {
    rule_id: "AB-020",
    category: "machine_readable",
    icon: "🛠️",
    title: "MCP Tools List",
    short_description: "Your MCP server responds to tool listing requests.",
    user_value: "Agents need to see what tools your MCP server offers before they can use any of them.",
    wrong_example: "MCP server doesn't respond to tool listing. Agents don't know what's available.",
    right_example: "MCP server lists all available tools with descriptions.",
    effort_hint: "moderate",
    estimated_cost: "$10-50",
  },
  {
    rule_id: "AB-021",
    category: "machine_readable",
    icon: "📞",
    title: "MCP Tool Calls",
    short_description: "Your MCP server responds when agents try to call a tool.",
    user_value: "Listing tools isn't enough — agents need to actually call them. If calls fail, your MCP server is useless.",
    wrong_example: "MCP server lists tools but doesn't respond when agents try to use them.",
    right_example: "MCP server processes tool calls and returns results.",
    effort_hint: "moderate",
    estimated_cost: "$10-50",
  },
  {
    rule_id: "AB-022",
    category: "machine_readable",
    icon: "📡",
    title: "MCP Streaming Support",
    short_description: "Your MCP server supports streaming connections for real-time communication.",
    user_value: "Streaming lets agents get results as they're produced, which is essential for long-running tasks.",
    wrong_example: "MCP server only supports one-shot requests. Long tasks time out.",
    right_example: "MCP server supports streaming, so agents get results in real time.",
    effort_hint: "complex",
    estimated_cost: "$100+",
  },

  // ─── Verification (1 rule) ───────────────────────────
  {
    rule_id: "AB-013",
    category: "verification",
    icon: "✅",
    title: "Owner Verification",
    short_description: "Your site can prove that you own the domain and are who you claim to be.",
    user_value: "Verification builds trust. Agents are more likely to interact with verified sites than anonymous ones.",
    wrong_example: "No verification mechanism. Agents can't confirm you're legitimate.",
    right_example: "Domain ownership is verified, so agents know you're the real deal.",
    effort_hint: "complex",
    estimated_cost: "$100+",
  },

  // ─── Content Negotiation (7 rules) ───────────────────
  {
    rule_id: "AB-015",
    category: "content_negotiation",
    icon: "🤖",
    title: "Agent User-Agent Format",
    short_description: "Your site serves appropriate content when an AI agent visits.",
    user_value: "When an AI agent visits your site, it should get content optimized for machines, not a web page designed for humans.",
    wrong_example: "AI agents get the same HTML as human visitors. They can't parse it efficiently.",
    right_example: "AI agents get clean, structured content optimized for their needs.",
    effort_hint: "moderate",
    estimated_cost: "$10-50",
  },
  {
    rule_id: "AB-016",
    category: "content_negotiation",
    icon: "📊",
    title: "JSON Format Support",
    short_description: "Your site returns JSON when an agent requests it.",
    user_value: "JSON is the universal language for APIs. If agents can't get JSON, they can't use your data.",
    wrong_example: "Requesting JSON always returns HTML. Agents can't extract data.",
    right_example: "Requesting JSON returns clean JSON data that agents can parse.",
    effort_hint: "moderate",
    estimated_cost: "$10-50",
  },
  {
    rule_id: "AB-017",
    category: "content_negotiation",
    icon: "📝",
    title: "Plain Text Format Support",
    short_description: "Your site returns plain text when an agent requests it.",
    user_value: "Some AI models work best with plain text. Offering it makes your content accessible to more agents.",
    wrong_example: "Only HTML and JSON available. Text-only AI models can't use your content.",
    right_example: "Plain text is available for AI models that prefer it.",
    effort_hint: "quick",
    estimated_cost: "$0",
  },
  {
    rule_id: "AB-018",
    category: "content_negotiation",
    icon: "⬇️",
    title: "Markdown Format Support",
    short_description: "Your site returns Markdown when an agent requests it.",
    user_value: "Markdown is the preferred format for many AI systems. Offering it makes your content easy to consume.",
    wrong_example: "No Markdown option. AI models have to convert from HTML, losing formatting.",
    right_example: "Markdown is available, preserving formatting for AI consumption.",
    effort_hint: "quick",
    estimated_cost: "$0",
  },
  {
    rule_id: "AB-019",
    category: "content_negotiation",
    icon: "🎯",
    title: "Preferred Format Selection",
    short_description: "Your site respects format preferences when agents specify what they want.",
    user_value: "When an agent says 'I prefer JSON over HTML', your site should honor that preference.",
    wrong_example: "Format preferences are ignored. Agents get whatever the server decides.",
    right_example: "Format preferences are respected, so agents get exactly what they asked for.",
    effort_hint: "moderate",
    estimated_cost: "$10-50",
  },
  {
    rule_id: "AB-028",
    category: "content_negotiation",
    icon: "🔀",
    title: "Vary Header",
    short_description: "Your site tells caches that content varies based on the requested format.",
    user_value: "Without a Vary header, caches may serve the wrong format to agents — JSON to someone who asked for HTML.",
    wrong_example: "No Vary header. Caches serve stale or wrong formats.",
    right_example: "Vary header ensures each agent gets the correct format from caches.",
    effort_hint: "quick",
    estimated_cost: "$0",
  },
  {
    rule_id: "AB-029",
    category: "content_negotiation",
    icon: "📍",
    title: "No Redirect on Negotiation",
    short_description: "Your site serves the requested format directly without redirecting.",
    user_value: "Redirects slow agents down and can break some clients. Direct responses are faster and more reliable.",
    wrong_example: "Requesting JSON redirects to a different URL. Some agents can't follow redirects.",
    right_example: "The requested format is served directly at the same URL.",
    effort_hint: "quick",
    estimated_cost: "$0",
  },

  // ─── Payments (9 rules) ──────────────────────────────
  {
    rule_id: "AB-030",
    category: "payments",
    icon: "💰",
    title: "Paid Endpoint Response",
    short_description: "When an agent tries to access a paid feature, your site responds with a clear payment request.",
    user_value: "This is how agents know a feature costs money and how to pay. Without it, agents hit a wall and move on.",
    wrong_example: "Paid endpoints return a generic error. Agents don't know payment is required.",
    right_example: "Paid endpoints clearly communicate the price and payment method.",
    effort_hint: "complex",
    estimated_cost: "$100+",
  },
  {
    rule_id: "AB-031",
    category: "payments",
    icon: "🔓",
    title: "Payment Challenge Decodable",
    short_description: "The payment request your site sends is properly formatted and can be decoded by agents.",
    user_value: "If agents can't decode the payment request, they can't pay — even if they want to.",
    wrong_example: "Payment request is malformed. Agents can't parse it to know what to pay.",
    right_example: "Payment request is well-formed and agents can decode it to complete payment.",
    effort_hint: "complex",
    estimated_cost: "$100+",
  },
  {
    rule_id: "AB-032",
    category: "payments",
    icon: "📋",
    title: "Payment Required Header",
    short_description: "Your payment responses include a header that tells agents payment is needed.",
    user_value: "This header is the universal signal for 'payment required'. Without it, agents don't know to look for payment details.",
    wrong_example: "No payment header. Agents don't realize they need to pay.",
    right_example: "Payment header clearly signals that payment is required.",
    effort_hint: "moderate",
    estimated_cost: "$10-50",
  },
  {
    rule_id: "AB-033",
    category: "payments",
    icon: "👤",
    title: "Payment Recipient",
    short_description: "Your payment requests specify who should receive the payment.",
    user_value: "Agents need to know where to send money. Without a recipient, payment is impossible.",
    wrong_example: "No recipient specified. Agents don't know who to pay.",
    right_example: "Payment recipient is clearly specified.",
    effort_hint: "moderate",
    estimated_cost: "$10-50",
  },
  {
    rule_id: "AB-034",
    category: "payments",
    icon: "💵",
    title: "Payment Amount",
    short_description: "Your payment requests specify how much the agent needs to pay.",
    user_value: "Without a clear price, agents can't decide whether a feature is worth paying for.",
    wrong_example: "No amount specified. Agents don't know how much the service costs.",
    right_example: "Price is clearly stated in the payment request.",
    effort_hint: "moderate",
    estimated_cost: "$10-50",
  },
  {
    rule_id: "AB-035",
    category: "payments",
    icon: "📄",
    title: "Payment Discovery File",
    short_description: "Your site publishes a file that describes all payment options in one place.",
    user_value: "A payment discovery file lets agents understand your pricing model before making any requests.",
    wrong_example: "No payment discovery file. Agents have to trigger paid endpoints to learn pricing.",
    right_example: "A published file describes all payment options upfront.",
    effort_hint: "moderate",
    estimated_cost: "$10-50",
  },
  {
    rule_id: "AB-038",
    category: "payments",
    icon: "🏦",
    title: "Payment Facilitator",
    short_description: "Your payment requests specify a facilitator that can process the payment.",
    user_value: "A facilitator handles the payment mechanics. Without one, agents can't complete transactions.",
    wrong_example: "No facilitator specified. Agents don't know how to process the payment.",
    right_example: "A facilitator is specified, so agents know how to complete payment.",
    effort_hint: "complex",
    estimated_cost: "$100+",
  },
  {
    rule_id: "AB-070",
    category: "payments",
    icon: "⚡",
    title: "Lightning Payment Support",
    short_description: "Your site supports Lightning Network payments for instant, low-cost transactions.",
    user_value: "Lightning payments are instant and cost fractions of a cent — ideal for micro-transactions between agents.",
    wrong_example: "Only traditional payment methods. Slow and expensive for small agent transactions.",
    right_example: "Lightning payments enable instant micro-transactions between agents.",
    effort_hint: "complex",
    estimated_cost: "$100+",
  },
  {
    rule_id: "AB-071",
    category: "payments",
    icon: "🎫",
    title: "Lightning Payment Details",
    short_description: "Your Lightning payment responses include all required details for agents to pay.",
    user_value: "Lightning payments require specific details. Missing any of them means the payment can't be completed.",
    wrong_example: "Lightning payment response is incomplete. Agents can't complete the transaction.",
    right_example: "All required Lightning payment details are included.",
    effort_hint: "complex",
    estimated_cost: "$100+",
  },

  // ─── Bazaar (3 rules) ────────────────────────────────
  {
    rule_id: "AB-036",
    category: "bazaar",
    icon: "🏪",
    title: "Bazaar Discoverable",
    short_description: "Your agent marketplace listings can be discovered by other agents.",
    user_value: "The Bazaar is where agents find services to use. If you're not discoverable, you're invisible to the agent economy.",
    wrong_example: "Not listed in the Bazaar. Other agents can't find or use your services.",
    right_example: "Your services are discoverable in the Bazaar marketplace.",
    effort_hint: "moderate",
    estimated_cost: "$10-50",
  },
  {
    rule_id: "AB-037",
    category: "bazaar",
    icon: "🏷️",
    title: "Bazaar Service Declared",
    short_description: "Your site declares what services it offers in the Bazaar marketplace.",
    user_value: "A declared service tells other agents exactly what you offer, so they can decide to use it.",
    wrong_example: "Present in Bazaar but no services declared. Agents don't know what you offer.",
    right_example: "Services are clearly declared in the Bazaar for other agents to discover.",
    effort_hint: "moderate",
    estimated_cost: "$10-50",
  },
  {
    rule_id: "AB-072",
    category: "bazaar",
    icon: "🛒",
    title: "Bazaar in Lightning Payments",
    short_description: "Your Lightning payment responses include Bazaar marketplace information.",
    user_value: "This connects your payment system with the marketplace, so agents can discover and pay for services in one flow.",
    wrong_example: "Lightning payments work but don't include Bazaar info. Agents miss marketplace opportunities.",
    right_example: "Bazaar info is included in payment responses, connecting payments to the marketplace.",
    effort_hint: "complex",
    estimated_cost: "$100+",
  },

  // ─── OpenAPI (6 rules) ───────────────────────────────
  {
    rule_id: "AB-039",
    category: "openapi",
    icon: "📋",
    title: "API Spec at Standard Location",
    short_description: "Your API specification is published at the standard location agents expect.",
    user_value: "Agents look for API specs in standard places. If yours is elsewhere, they may never find it.",
    wrong_example: "API spec exists but at a non-standard URL. Agents don't know where to look.",
    right_example: "API spec is at the standard location, so agents find it immediately.",
    effort_hint: "quick",
    estimated_cost: "$0",
  },
  {
    rule_id: "AB-040",
    category: "openapi",
    icon: "🛤️",
    title: "API Paths Defined",
    short_description: "Your API specification lists all available paths and endpoints.",
    user_value: "Without defined paths, agents don't know what endpoints exist or how to call them.",
    wrong_example: "API spec is mostly empty. No paths defined.",
    right_example: "All API paths are defined with parameters and responses.",
    effort_hint: "complex",
    estimated_cost: "$100+",
  },
  {
    rule_id: "AB-041",
    category: "openapi",
    icon: "🌐",
    title: "API Paths Reachable",
    short_description: "All endpoints defined in your API spec actually work when agents call them.",
    user_value: "A spec that lists endpoints that don't work is worse than no spec — it wastes agents' time and breaks trust.",
    wrong_example: "API spec lists 10 endpoints, but 3 of them return errors.",
    right_example: "Every endpoint in the spec works as described.",
    effort_hint: "moderate",
    estimated_cost: "$10-50",
  },
  {
    rule_id: "AB-042",
    category: "openapi",
    icon: "🔍",
    title: "Response Matches Spec",
    short_description: "Your API responses match what your specification promises.",
    user_value: "If responses don't match the spec, agents get errors they can't predict. Consistency is key for trust.",
    wrong_example: "Spec says response has 'name' field, but actual response has 'username'. Agents break.",
    right_example: "Responses exactly match the specification.",
    effort_hint: "moderate",
    estimated_cost: "$10-50",
  },
  {
    rule_id: "AB-043",
    category: "openapi",
    icon: "🔢",
    title: "API Version Identified",
    short_description: "Your API specification clearly states which version it is.",
    user_value: "Version info lets agents handle changes gracefully. Without it, updates can break agent integrations silently.",
    wrong_example: "No version in the spec. Agents don't know if the API has changed.",
    right_example: "Version is clearly identified, so agents can adapt to changes.",
    effort_hint: "quick",
    estimated_cost: "$0",
  },
  {
    rule_id: "AB-044",
    category: "openapi",
    icon: "🏷️",
    title: "API Title",
    short_description: "Your API specification has a clear title that describes your service.",
    user_value: "A descriptive title helps agents understand what your API does at a glance.",
    wrong_example: "API spec has no title or a generic one like 'API'.",
    right_example: "A clear title like 'AgentBadge Passport API' tells agents exactly what it is.",
    effort_hint: "quick",
    estimated_cost: "$0",
  },

  // ─── Skills (3 rules) ────────────────────────────────
  {
    rule_id: "AB-026",
    category: "skills",
    icon: "🎯",
    title: "Skill File Present",
    short_description: "Your site has a skill file that describes specialized capabilities agents can use.",
    user_value: "Skill files let agents discover advanced features of your service that aren't part of your main API.",
    wrong_example: "No skill file. Agents only see your basic API and miss advanced features.",
    right_example: "A skill file describes specialized capabilities agents can use.",
    effort_hint: "moderate",
    estimated_cost: "$10-50",
  },
  {
    rule_id: "AB-027",
    category: "skills",
    icon: "✓",
    title: "Skill File Format Valid",
    short_description: "Your skill file follows the expected format with proper metadata.",
    user_value: "A malformed skill file causes errors. A valid one ensures agents can parse and use your skills.",
    wrong_example: "Skill file exists but has invalid format. Agents get errors when parsing it.",
    right_example: "Skill file is properly formatted with all required metadata.",
    effort_hint: "quick",
    estimated_cost: "$0",
  },
  {
    rule_id: "AB-065",
    category: "skills",
    icon: "📚",
    title: "Skills Index",
    short_description: "Your site has an index listing all available skills in one place.",
    user_value: "An index lets agents see all your skills at once, rather than discovering them one by one.",
    wrong_example: "Skills exist but there's no index. Agents have to find them individually.",
    right_example: "A skills index lists everything available for easy discovery.",
    effort_hint: "moderate",
    estimated_cost: "$10-50",
  },

  // ─── Agents.txt (1 rule) ─────────────────────────────
  {
    rule_id: "AB-048",
    category: "agents_txt",
    icon: "📜",
    title: "Agents.txt File",
    short_description: "Your site has an agents.txt file with instructions specifically for AI agents.",
    user_value: "Agents.txt is like robots.txt but for AI agents — it tells them what they can do and how to behave on your site.",
    wrong_example: "No agents.txt. AI agents don't know your preferences for how they should interact.",
    right_example: "A clear agents.txt guides AI agents on how to interact with your site.",
    effort_hint: "moderate",
    estimated_cost: "$10-50",
  },

  // ─── WebMCP (3 rules) ────────────────────────────────
  {
    rule_id: "AB-050",
    category: "webmcp",
    icon: "🌐",
    title: "WebMCP Manifest",
    short_description: "Your site has a WebMCP manifest that enables browser-based agent interactions.",
    user_value: "WebMCP lets agents interact with your site directly through the browser, opening up new interaction patterns.",
    wrong_example: "No WebMCP manifest. Browser-based agents can't interact with your site.",
    right_example: "A WebMCP manifest enables rich browser-based agent interactions.",
    effort_hint: "complex",
    estimated_cost: "$100+",
  },
  {
    rule_id: "AB-051",
    category: "webmcp",
    icon: "📝",
    title: "WebMCP Form Annotations",
    short_description: "Your forms are annotated so WebMCP agents can fill them automatically.",
    user_value: "Annotations let agents understand and fill your forms, enabling automated interactions like registration and checkout.",
    wrong_example: "Forms have no annotations. Agents can't understand what fields mean or how to fill them.",
    right_example: "Forms are annotated, so agents can fill them automatically and correctly.",
    effort_hint: "moderate",
    estimated_cost: "$10-50",
  },
  {
    rule_id: "AB-069",
    category: "webmcp",
    icon: "🖥️",
    title: "WebMCP Browser Tools",
    short_description: "Your site exposes browser-side tools that agents can call through WebMCP.",
    user_value: "Browser-side tools let agents perform actions that require a browser context, like rendering or interaction.",
    wrong_example: "No browser-side tools. Agents are limited to server-side API calls.",
    right_example: "Browser-side tools enable agents to perform rich interactions.",
    effort_hint: "complex",
    estimated_cost: "$100+",
  },

  // ─── Identity (2 rules) ──────────────────────────────
  {
    rule_id: "AB-056",
    category: "identity",
    icon: "🪪",
    title: "WebFinger Identity Lookup",
    short_description: "Your site can answer 'who is this?' queries from AI agents.",
    user_value: "Agents need to verify your identity before trusting your API. Without this, you're an anonymous server that agents will avoid.",
    wrong_example: "No identity endpoint. Agents have no way to verify who you are.",
    right_example: "Agents can look up your identity and confirm you're a legitimate service.",
    effort_hint: "moderate",
    estimated_cost: "$10-50",
  },
  {
    rule_id: "AB-057",
    category: "identity",
    icon: "🆔",
    title: "DID Document",
    short_description: "Your site provides a Decentralized Identifier document for on-chain identity verification.",
    user_value: "A DID document lets agents verify your identity on the blockchain, providing cryptographic proof of who you are.",
    wrong_example: "No DID document. Agents can't verify your identity cryptographically.",
    right_example: "A DID document provides cryptographic proof of your identity.",
    effort_hint: "complex",
    estimated_cost: "$100+",
  },

  // ─── Bot Authentication (6 rules) ────────────────────
  {
    rule_id: "AB-023",
    category: "bot_auth",
    icon: "🔐",
    title: "MCP Auth Discovery",
    short_description: "Your MCP server's authentication info is discoverable by agents.",
    user_value: "Agents need to find auth info before connecting to your MCP server. Without discovery, they can't authenticate.",
    wrong_example: "MCP server requires auth but doesn't publish how to get it.",
    right_example: "Auth discovery is available, so agents know how to authenticate.",
    effort_hint: "moderate",
    estimated_cost: "$10-50",
  },
  {
    rule_id: "AB-058",
    category: "bot_auth",
    icon: "✍️",
    title: "Bot Signatures Directory",
    short_description: "Your site has a directory of bot signatures for verifying AI agent identities.",
    user_value: "A signatures directory lets you verify which bot is making a request, enabling trust-based access control.",
    wrong_example: "No signatures directory. You can't tell which bot is calling your API.",
    right_example: "A signatures directory lets you identify and trust specific bots.",
    effort_hint: "complex",
    estimated_cost: "$100+",
  },
  {
    rule_id: "AB-059",
    category: "bot_auth",
    icon: "👥",
    title: "Bot Directory Members",
    short_description: "Your bot signatures directory has valid, recognized members.",
    user_value: "A directory with invalid members is useless. Valid members enable real bot identification.",
    wrong_example: "Bot directory exists but members are invalid or unrecognized.",
    right_example: "All members in the bot directory are valid and recognized.",
    effort_hint: "moderate",
    estimated_cost: "$10-50",
  },
  {
    rule_id: "AB-060",
    category: "bot_auth",
    icon: "🔑",
    title: "Bot Public Keys",
    short_description: "Public keys for verified bots are reachable and valid.",
    user_value: "Public keys are needed to verify bot signatures. If they're unreachable, signature verification fails.",
    wrong_example: "Public keys are listed but unreachable. Signature verification fails.",
    right_example: "All public keys are reachable and valid for signature verification.",
    effort_hint: "moderate",
    estimated_cost: "$10-50",
  },
  {
    rule_id: "AB-063",
    category: "bot_auth",
    icon: "🛡️",
    title: "Protected Resource Metadata",
    short_description: "Your site publishes metadata about what resources are protected and how.",
    user_value: "This metadata tells agents which endpoints need authentication and what type, so they know before making requests.",
    wrong_example: "No protected resource metadata. Agents don't know which endpoints need auth.",
    right_example: "Protected resource metadata clearly indicates which endpoints need auth and how.",
    effort_hint: "moderate",
    estimated_cost: "$10-50",
  },
  {
    rule_id: "AB-067",
    category: "bot_auth",
    icon: "📜",
    title: "Web Bot Auth Directory",
    short_description: "Your site has a directory for web-based bot authentication using HTTP message signatures.",
    user_value: "This enables a standardized way for bots to prove their identity when making HTTP requests to your site.",
    wrong_example: "No web bot auth directory. Bots can't prove who they are when calling your API.",
    right_example: "A web bot auth directory enables standardized bot identification.",
    effort_hint: "complex",
    estimated_cost: "$100+",
  },

  // ─── Infrastructure (3 rules) ────────────────────────
  {
    rule_id: "AB-045",
    category: "infrastructure",
    icon: "⚡",
    title: "Cache Headers",
    short_description: "Your site sends cache headers so agents and CDNs know how to cache your content.",
    user_value: "Proper caching means faster responses for agents and lower server costs for you.",
    wrong_example: "No cache headers. Every request hits your server, slowing agents down.",
    right_example: "Cache headers enable efficient caching, speeding up agent requests.",
    effort_hint: "quick",
    estimated_cost: "$0",
  },
  {
    rule_id: "AB-046",
    category: "infrastructure",
    icon: "🚫",
    title: "Structured 404 Errors",
    short_description: "Your site returns structured JSON for 404 errors instead of plain HTML.",
    user_value: "When agents hit a missing page, a structured error tells them what went wrong. An HTML 404 page is useless to machines.",
    wrong_example: "404 returns an HTML page. Agents can't parse the error.",
    right_example: "404 returns structured JSON with error details agents can understand.",
    effort_hint: "quick",
    estimated_cost: "$0",
  },
  {
    rule_id: "AB-047",
    category: "infrastructure",
    icon: "⏱️",
    title: "Rate Limit Headers",
    short_description: "Your site sends rate limit headers so agents know how many requests they can make.",
    user_value: "Rate limit headers let agents pace themselves and avoid getting blocked.",
    wrong_example: "No rate limit headers. Agents get blocked without warning.",
    right_example: "Rate limit headers tell agents exactly how many requests they have left.",
    effort_hint: "quick",
    estimated_cost: "$0",
  },
  {
    rule_id: "AB-073",
    category: "infrastructure",
    icon: "🔒",
    title: "HTTPS Redirect Enforced",
    short_description: "Your site automatically redirects HTTP requests to HTTPS so agents always use a secure connection.",
    user_value: "Agents expect secure connections. Without HTTPS redirect, agents may fail or warn users about insecure endpoints.",
    wrong_example: "HTTP requests return content without redirecting. Agents get insecure responses.",
    right_example: "HTTP requests redirect to HTTPS automatically. Agents always connect securely.",
    effort_hint: "quick",
    estimated_cost: "$0",
  },
  {
    rule_id: "AB-076",
    category: "openapi",
    icon: "🛤️",
    title: "OpenAPI Paths Reachable",
    short_description: "At least half the paths declared in your OpenAPI spec return valid responses when probed.",
    user_value: "An OpenAPI spec with unreachable paths misleads agents. Reachable paths mean agents can actually use your API.",
    wrong_example: "OpenAPI declares 10 paths but only 2 respond. Agents waste calls on dead endpoints.",
    right_example: "Most declared paths respond correctly. Agents can rely on your spec to navigate your API.",
    effort_hint: "moderate",
    estimated_cost: "$10-50",
  },
  {
    rule_id: "AB-077",
    category: "openapi",
    icon: "📋",
    title: "OpenAPI Response Matches Spec",
    short_description: "Your API responses match the structure declared in your OpenAPI specification.",
    user_value: "When responses match the spec, agents can parse them reliably. Mismatches cause parsing errors and broken integrations.",
    wrong_example: "Spec says response has a 'data' array but the actual response returns an object. Agents crash trying to parse it.",
    right_example: "Responses match the spec exactly. Agents parse responses without surprises.",
    effort_hint: "moderate",
    estimated_cost: "$10-50",
  },
  {
    rule_id: "AB-078",
    category: "openapi",
    icon: "💳",
    title: "Payment Info in OpenAPI",
    short_description: "Your OpenAPI spec declares payment information for paid operations so agents know which endpoints cost money.",
    user_value: "Agents need to know which operations require payment before calling them. Declaring payment info prevents unexpected charges.",
    wrong_example: "Paid endpoints have no payment info in the spec. Agents call them and get surprise 402 errors.",
    right_example: "Paid operations clearly declare payment info. Agents know upfront which calls cost money.",
    effort_hint: "moderate",
    estimated_cost: "$10-50",
  },
  {
    rule_id: "AB-074",
    category: "actionability",
    icon: "🤝",
    title: "A2A Agent Card Published",
    short_description: "Your agent publishes a /.well-known/agent-card.json file so other agents can discover its capabilities via the A2A protocol.",
    user_value: "Agent Cards let other agents know what your agent can do, enabling autonomous discovery and inter-agent collaboration.",
    wrong_example: "No /.well-known/agent-card.json exists. Other agents cannot discover your agent's A2A capabilities.",
    right_example: "A valid agent-card.json is published at /.well-known/ with agent metadata per the A2A specification.",
    effort_hint: "quick",
    estimated_cost: "$0",
  },
  {
    rule_id: "AB-075",
    category: "actionability",
    icon: "✅",
    title: "A2A Agent Card Verified",
    short_description: "Your agent-card.json includes all required fields: name, description, url, and capabilities.",
    user_value: "A complete Agent Card ensures other agents can properly identify and interact with your agent.",
    wrong_example: "Agent card exists but is missing required fields like capabilities or url, making it unusable.",
    right_example: "Agent card includes name, description, url, and capabilities — all required A2A fields present.",
    effort_hint: "quick",
    estimated_cost: "$0",
  },
  {
    rule_id: "AB-085",
    category: "actionability",
    icon: "🔌",
    title: "MCP Server Name Present",
    short_description: "Your MCP server's initialize response includes serverInfo.name, allowing agents to identify the server.",
    user_value: "Agents need to know which MCP server they're connected to for tool routing and debugging.",
    wrong_example: "MCP initialize response has no serverInfo.name. Agents can't identify the server.",
    right_example: "MCP initialize response includes serverInfo.name as a non-empty string.",
    effort_hint: "quick",
    estimated_cost: "$0",
  },
  {
    rule_id: "AB-086",
    category: "actionability",
    icon: "🔐",
    title: "MCP Auth Discovery Resolves",
    short_description: "If your MCP descriptor declares authentication, the auth URL is reachable and returns valid metadata.",
    user_value: "Agents need to resolve auth requirements before calling MCP tools. Broken auth discovery blocks all tool access.",
    wrong_example: "MCP descriptor declares auth but the auth URL returns 404 or is unreachable.",
    right_example: "MCP auth discovery URL returns 200 with valid authentication metadata.",
    effort_hint: "moderate",
    estimated_cost: "$10-50",
  },
];
