#!/usr/bin/env bash
# SLICE-152-7: Circle Grant evidence collector.
#
# Reads the venue index (.data/venue.json — JSON VenueStore backend) and
# generates docs/GRANTS/circle-venue/evidence.md: per-job tx table with
# explorer links + stats snapshot + latest smoke-suite reports.
#
# Usage:
#   ./scripts/grants/collect-evidence.sh            # writes evidence.md
#   EVIDENCE_OUT=/tmp/ev.md ./scripts/grants/...     # custom output
#
# Env:
#   VENUE_INDEX_JSON  — venue index path   (default .data/venue.json)
#   SMOKE_DIR         — smoke reports dir  (default ../../packages/
#                       circle-payments/artifacts relative to server root)
#   ARC_EXPLORER_URL  — explorer base      (default https://explorer.arc.io)
#   VENUE_PAGE        — public venue URL   (default https://agentbadge.xyz/market)
set -euo pipefail
cd "$(dirname "$0")/../.."

VENUE_JSON="${VENUE_INDEX_JSON:-.data/venue.json}"
SMOKE_DIR="${SMOKE_DIR:-../../packages/circle-payments/artifacts}"
EXPLORER="${ARC_EXPLORER_URL:-https://explorer.arc.io}"
VENUE_PAGE="${VENUE_PAGE:-https://agentbadge.xyz/market}"
OUT="${EVIDENCE_OUT:-../../docs/GRANTS/circle-venue/evidence.md}"
TMP_BODY="$(mktemp)"

if [ ! -f "$VENUE_JSON" ]; then
  echo "WARN: $VENUE_JSON not found — emitting empty evidence" >&2
fi

mkdir -p "$(dirname "$OUT")"
export VENUE_JSON SMOKE_DIR EXPLORER VENUE_PAGE

jq -r '
  ($ENV.EXPLORER | rtrimstr("/")) as $ex |
  ([.jobs // {} | to_entries[] | .value]) as $jobs |
  ([.offers // {} | to_entries[] | .value]) as $offers |

  def txlink($h): if $h == null or $h == "" then "—" else "[`" + ($h | .[0:10]) + "…`](" + $ex + "/tx/" + $h + ")" end;
  def tscell($j; $k): ($j.chainTxs[$k] // null) as $h | txlink($h);

  "### Venue transactions\n" +
  "| job | status | budget | created | funded | submitted | completed | feedback |\n" +
  "|---|---|---|---|---|---|---|---|\n" +
  ([$jobs[] | . as $j |
    "| [" + .jobId + "](" + $ENV.VENUE_PAGE + "/jobs/" + .jobId + ") | " +
    .status + " | $" + ((.budgetUsdc // 0) | tostring) + " | " +
    tscell($j; "created") + " | " + tscell($j; "funded") + " | " +
    tscell($j; "submitted") + " | " + tscell($j; "completed") + " | " +
    txlink(.feedback.txHash) + " |"
  ] | join("\n")) +
  "\n\n### Stats snapshot\n" +
  "- jobsTotal: **" + ($jobs | length | tostring) + "**\n" +
  "- jobsDone: **" + ([$jobs[] | select(.status == "completed")] | length | tostring) + "**\n" +
  "- usdcVolume: **$" + ([$jobs[] | .budgetUsdc // 0] | add // 0 | tostring) + "**\n" +
  "- feedbackSent: **" + ([$jobs[] | select(.feedback.status == "sent")] | length | tostring) + "**\n" +
  "- providersActive: **" + ([$offers[] | select(.active == true)] | length | tostring) + "**\n"
' "$VENUE_JSON" > "$TMP_BODY" 2>/dev/null || {
  echo "WARN: jq parse failed on $VENUE_JSON — emitting empty evidence" >&2
  : > "$TMP_BODY"
}

# Latest smoke reports per network (if present)
smoke_section() {
  local net="$1" f
  f="$(ls -t "$SMOKE_DIR"/smoke-report-arc-"$net"-*.json 2>/dev/null | head -1 || true)"
  if [ -n "$f" ] && [ -f "$f" ]; then
    jq -r --arg f "$(basename "$f")" --arg net "$net" '
      "- **\($net)** — `\($f)` — ok: **\(.ok)**, started: \(.startedAt)" +
      ([.phases[]? | "\n  - \(.name): \(.ok // .status)"] | join(""))
    ' "$f"
  else
    echo "- **$net** — no report found"
  fi
}
SMOKE_MD="$(smoke_section testnet; smoke_section mainnet)"

{
  echo "# Venue evidence — $(date -Is)"
  echo
  echo "Auto-generated by \`scripts/grants/collect-evidence.sh\`."
  echo "Index: \`$VENUE_JSON\` · Explorer: <$EXPLORER>"
  echo
  cat "$TMP_BODY"
  echo
  echo "### Smoke-suite reports"
  echo "$SMOKE_MD"
} > "$OUT"

rm -f "$TMP_BODY"
echo "wrote $OUT"
