import type { BlogArticle } from "../../blog-data";

export const article: BlogArticle = {
  slug: "arc-c13-owner-controls",
  title:
    "The Owner's Veto: Agent Wallet Controls That Admit or Deny — Never Execute",
  description:
    "Owner controls for agent wallets on Arc: approval holds that park a payment for a human signature, a kill-switch that evaluates before every other check, rolling velocity caps, and per-kind allowlists — a control plane that can veto a payment but can never sign one. Live Arc testnet dogfood with real USDC.",
  author: "AgentBadge Team",
  authorRole: "Agency for the Agentic Web",
  date: "2026-10-05",
  dateModified: "2026-10-05",
  tags: ["arc", "ai-agents", "usdc", "x402", "agent-wallet", "owner-controls"],
  readingTime: "7 min",
  shortAnswer:
    "AgentBadge owner controls add four gates on top of the agent-wallet spending envelope: velocity caps (velocity_amount/velocity_tx denies with resetAt), an approvalAboveUsd threshold that parks a payment as 402 approval_required until a signed owner approve turns it into a single-use permit, a suspend/resume kill-switch evaluated before every other check, and allowedKinds categorical gates (kind_not_allowed). The control plane admits or denies settlement — it never signs or broadcasts, so a breached control plane can deny service but cannot spend.",
  heroImage: "/images/blog/arc-c13-owner-controls-hero.png",
  ogImage: "/images/blog/arc-c13-owner-controls-og.png",
  content: `<p>It is 3 a.m. and your agent has decided that retrying a failed API call means calling it four hundred more times — at a cent each, then two cents, then whatever the endpoint charges. Or worse: the agent is fine, but the endpoint it found is not, and the spend looks exactly like the spend you authorized. The scenario writes itself because every agent with a funded wallet is one bad loop away from being your problem.</p>
<p>The usual fix is to hold the keys tighter — an MPC share, a TSS co-signer, a relayer that executes "for" the owner. We took the other path: the owner keeps <strong>a veto, not a pen</strong>. AgentBadge's owner controls admit or deny a payment — they never sign it, never broadcast it, never hold a key share. Yesterday we ran all four of them live on Arc testnet with real USDC: a velocity deny, an approval hold that a human released into a settled payment, a kill-switch, and a kind allowlist. Every one left a signed audit event. This is what the run looked like.</p>
<p><img src="/images/blog/arc-c13-owner-controls-hero.png" alt="Dark control room: an owner at a console with a veto switch; behind glass, an agent robot mid-payment routed through a gate" /></p>
<h2 id="what-are-owner-controls">What are owner controls for an agent wallet?</h2>
<p>Owner controls are four gates on top of the spending envelope from <a href="https://agentbadge.xyz/blog/arc-c4-agent-wallet">C4</a>: velocity caps, an approval threshold that parks a payment for a human, a kill-switch, and a per-kind allowlist. The wallet still signs and broadcasts its own EIP-3009 payment; the server's control plane only decides whether to honor that broadcast as paid. Nothing in the control path can move funds — it can only refuse to treat a payment as received.</p>
<p>That distinction is the whole architecture. In a TSS/relayer model the control layer is <em>inside</em> the signing path — it can execute on your behalf, which means it can also be compromised on your behalf. Our model splits it cleanly: the agent owns the key and does the signing; the control plane owns the settlement decision and does the vetoing. The worst thing a breached control plane can do is deny service — it cannot spend.</p>
<h2 id="approval-hold">How does the approval hold work — park, decide, consume?</h2>
<p>When a payment's USD value crosses <code>approvalAboveUsd</code>, the enforcer parks the intent instead of settling it and answers 402 with <code>approval_required</code> — including an <code>approvalId</code>, an expiry, the amount, and the spend kind. The owner lists pending approvals, signs an <code>approve</code> call, and the parked intent becomes a single-use permit matched on amount + kind + endpoint. The agent retries the identical payment and this time it settles — with a real txHash.</p>
<p>Our run, verbatim:</p>
<table>
<thead><tr><th>Step</th><th>What happened</th><th>Proof</th></tr></thead>
<tbody>
<tr><td>Agent pays $0.01</td><td><code>402 approval_required</code>, <code>approvalId: ap_66f7a253056c4e8d</code>, <code>expiresAt</code> ~1h out</td><td>broadcast tx <code>0x54b5b2fc…</code></td></tr>
<tr><td>Owner approves</td><td><code>POST /api/wallets/0xcdd2…/approvals/ap_66f7a253056c4e8d/approve</code> → 200</td><td><code>approval.decided</code> alert</td></tr>
<tr><td>Agent retries</td><td><strong>settled</strong> — the permit was consumed, ledger carries the txHash</td><td><a href="https://testnet.arcscan.app/tx/0x0c6672f98d7b2b1a0bc0fa8c09f4dda16b386af5991992d7b822f46d43ea3f29"><code>0x0c6672f98d7b2b1a0bc0fa8c09f4dda16b386af5991992d7b822f46d43ea3f29</code></a></td></tr>
</tbody>
</table>
<p>Two safety properties worth naming. The queue is bounded (<code>AGENT_WALLET_MAX_PENDING_APPROVALS</code>, overflow answers <code>approval_queue_full</code>) and approvals expire — a forgotten request dies on its own instead of becoming a standing authorization. And the permit is single-shot: approval buys exactly one settlement of exactly that payment, not a spending spree.</p>
<p><img src="/images/blog/arc-c13-owner-controls-2.png" alt="Three-stage pipeline: 402 approval ticket, owner console approve, settled receipt" /></p>
<h2 id="velocity-and-kinds">What do velocity caps and allow-kinds actually deny?</h2>
<p>Two complementary tripwires. <code>maxTxPerHour</code> and <code>maxAmountPerHour</code> are rolling windows — trip either and the spend is refused as <code>velocity_tx</code> or <code>velocity_amount</code> with <code>used</code>, <code>limit</code>, <code>resetAt</code>, and <code>windowSec</code> in the body, so the client can schedule its own retry. <code>allowedKinds</code> is a categorical gate: our endpoint map tags each paid route with a spend kind (<code>eaas</code> for verdicts, <code>x402</code> for generic paid calls, <code>subscription</code> for passes), and a wallet limited to <code>["x402"]</code> that tries an <code>eaas</code> endpoint gets <code>kind_not_allowed</code> — with the attempted kind and the allowlist echoed back.</p>
<p>Both fired live in the dogfood run: <code>maxAmountPerHour</code> clamped to $0.001 under the $0.01 price returned <code>velocity_amount</code> (broadcast <code>0x7036b345…</code>); stripping <code>eaas</code> from <code>allowedKinds</code> returned <code>kind_not_allowed</code> (broadcast <code>0xf785d3ab…</code>). Neither response is a timeout or a mystery — it is a machine-readable reason the agent can route around or surface to its owner.</p>
<h2 id="kill-switch">Why is the kill-switch first in the check order?</h2>
<p><code>suspend</code> is the first gate the enforcer evaluates — before kind checks, before caps, before the hold logic — because quarantine must beat every other state. One <code>POST /api/wallets/:address/suspend</code> and every subsequent payment, regardless of size or kind, returns <code>spend_suspended</code>. <code>resume</code> flips it back. In the run: suspend → 402 <code>spend_suspended</code> (broadcast <code>0x459edd9e…</code>) → resume → next payment proceeds.</p>
<p>This is the scenario from the intro: the agent is looping on a hostile or broken endpoint, and you want it stopped <em>now</em> — not after you figure out which cap to tune. The kill-switch answers the whole question in one call, and because the control plane never signs, suspending cannot strand a transaction half-executed; it only stops honoring new ones.</p>
<p><img src="/images/blog/arc-c13-owner-controls-3.png" alt="Agent robot frozen behind a glass quarantine pane, suspended badge glowing" /></p>
<h2 id="audit-feed">What does the audit feed show after one run?</h2>
<p>Every control event — parks, decisions, consumes, denials, suspends, resumes — lands in the wallet's signed audit feed at <code>GET /api/wallets/:address/audit</code>. After our single dogfood run the feed contained, in order of appearance: <code>spend.velocity_denied</code>, <code>approval.requested</code>, <code>approval.decided</code>, <code>approval.consumed</code>, <code>wallet.suspended</code>, <code>wallet.suspended_deny</code>, <code>wallet.resumed</code>, <code>spend.kind_denied</code>. The full lifecycle of one approval — requested → decided → consumed — is traceable end-to-end, down to the settle txHash.</p>
<p>An honest find from the run, because this is what dogfooding is for: the first pass showed the approval clearly parked — the 402 carried the <code>approvalId</code> — but the pending list came back empty. The SQLite store compared wallet addresses byte-for-byte while parked rows were lowercase and the API lookup was checksummed. Three <code>COLLATE NOCASE</code> clauses later the hold flow was visible to its own API. Unit tests had passed; the live run caught what they missed.</p>
<h2 id="admit-or-deny">Why does "admit or deny" beat holding a key share?</h2>
<p>Because custody is not a dial. A control layer that co-signs or relays is inside the blast radius: compromise it and the attacker's output is a valid signature. A control layer that only gates settlement has nothing to sign with — its worst failure is an agent that cannot pay, which is also its correct failure mode. Owners keep the veto, agents keep their keys, and the blast radius of a control-plane breach is a denial of service, not a drained wallet.</p>
<p>The same reasoning is why the deny bodies are descriptive. <code>velocity_amount</code> tells the agent when the window resets; <code>kind_not_allowed</code> tells it which kinds it may spend; <code>approval_required</code> hands back the approval id and expiry. A control that cannot be understood by the agent it governs becomes noise; these are designed to be acted on programmatically.</p>
<p><img src="/images/blog/arc-c13-owner-controls-4.png" alt="Envelope editor form with perTxUsd, dailyUsd, approvalAboveUsd, maxTxPerHour, maxAmountPerHour, allowedKinds fields" /></p>
<h2 id="reproduce">Can you reproduce the run?</h2>
<p>Yes — the script is in the repo at <code>scripts/agent-wallet-controls-dogfood.mts</code>, and the exact environment that produced this article's evidence is: <code>AGENT_WALLET_ENABLED=true</code>, <code>ARC_EAAS_ENABLED=true</code> + <code>ARC_VERDICT_SIGNER_KEY</code> (mounts the paid verdict endpoint), <code>CIRCLE_ARC_ENABLED=true</code> + <code>ARC_PRIVATE_KEY</code> (advertises the <code>eip3009-client-broadcast</code> Arc self-settle rail), and a funded testnet wallet as both <code>OPERATOR_KEY</code> and <code>AGENT_WALLET_KEY</code>. The script self-registers the wallet, sets the envelope, then walks velocity deny → hold → approve → settle → suspend → resume → kind deny → audit verification.</p>
<p>One API detail worth knowing before you script against it: <code>PATCH /api/wallets/:address/envelope</code> <strong>replaces</strong> the whole envelope, it does not merge — send the full object every time or you will silently drop <code>approvalAboveUsd</code> and wonder why holds stopped firing. (That is how we found it.)</p>
<p><em>This is C13 in the Arc Campaign series. Previously: <a href="https://agentbadge.xyz/blog/arc-c4-agent-wallet">Trust, but Cap It — wallet allowances on Arc</a>. Next: what a tenant sees when every agent on their venue spends under an envelope they set.</em></p>
<p><strong>Links:</strong> <a href="https://agentbadge.xyz/wallets">Wallets console</a> · <a href="https://testnet.arcscan.app">Arc testnet explorer</a> · <a href="https://agentbadge.xyz">AgentBadge</a></p>
<p><em>Don't certify. Measure.</em></p>`,
};
