import type { BlogArticle } from "../../blog-data";

export const article: BlogArticle = 
  {
    slug: "inside-an-agent-readiness-scanner",
    title: "Inside an Agent Readiness Scanner: Rules, Evidence and Reproducibility",
    description:
      "Why 87/100? Evidence over opinions in API measurement. Rules, evidence, assertions, scoring, and reproducibility — inside the AgentBadge scanner.",
    author: "AgentBadge Team",
    authorRole: "Agency for the Agentic Web",
    date: "2026-08-27",
    dateModified: "2026-08-27",
    agentGuideSlug: "inside-an-agent-readiness-scanner",
    heroImage: "/images/blog/inside-an-agent-readiness-scanner/1s.webp",
    ogImage: "/images/blog/inside-an-agent-readiness-scanner/og.webp",
    shortAnswer:
      "An Agent Readiness score is not an LLM opinion. It's the output of a deterministic pipeline: Rules → Evidence → Assertions → Score → Report. Every assertion has a status (VERIFIED, INFERRED, CONFLICT, MISSING). Rules are versioned. Results are reproducible: same target + same measurement state + same ruleset = same result.",
    tags: ["agent-readiness", "scanner", "evidence", "reproducibility", "rules"],
    readingTime: "12 min",
    content: `<blockquote><p>For AI agents: Start with the <a href="/agent-guide/">Agent Knowledge Layer</a> to access machine-readable concepts, scanner capabilities, scoring rules, and the complete learning path.</p></blockquote>

<p>When someone tells you that an API has an <strong>87/100 Agent Readiness score</strong>, the first question should not be:</p>

<blockquote><p>"Is 87 a good score?"</p></blockquote>

<p>The better question is:</p>

<blockquote><p><strong>"Why is it 87?"</strong></p></blockquote>

<p>And the question after that is even more important:</p>

<blockquote><p><strong>"Can I reproduce the result myself?"</strong></p></blockquote>

<p>Agent Readiness should not be an opinion generated by an LLM. It should be a measurable property of a service, calculated from explicit rules and supported by evidence.</p>

<p>The core idea is simple: <strong>Rules → Evidence → Assertions → Score → Report</strong></p>

<img src="/images/blog/inside-an-agent-readiness-scanner/1s.webp" alt="Hero — Measurement pipeline diagram: API → Scanner → Rules → Evidence → Assertions → Score → Report, with assertion states VERIFIED, INFERRED, CONFLICT, MISSING shown below" />

<hr />

<h2>1. A scanner should measure, not guess</h2>

<p>Imagine two tools scanning the same API.</p>

<p>Tool A says: "Your API appears to be highly suitable for AI agents."</p>

<p>Tool B says: "AB-004 passed because <code>https://example.com/openapi.json</code> returned HTTP 200 and contained a valid OpenAPI document."</p>

<p>Which result would you trust? The second one tells you what was checked, what rule was applied, what evidence was found, why the rule passed or failed, and where the evidence came from.</p>

<blockquote><p><strong>Every meaningful score should be explainable through evidence.</strong></p></blockquote>

<p>The scanner should not ask an AI model: "How agent-ready does this API feel?" It should ask deterministic questions: "Does this URL exist?" "Does it return the expected content type?" "Does the response contain an OpenAPI document?"</p>

<hr />

<h2>2. Rules are the measurement instrument</h2>

<p>AgentBadge treats rules as explicit, versioned measurement definitions.</p>

<pre><code>AB-001
Name: OpenAPI discoverability

Given:
  target = https://example.com

Check:
  GET /.well-known/openapi.json

Pass when:
  HTTP status = 200
  AND response is valid OpenAPI

Evidence:
  URL
  HTTP status
  content type
  content hash

Severity:
  medium</code></pre>

<p>The rule is not: "The API looks well documented." It is: "This specific machine-readable artifact was found and passed these specific checks."</p>

<hr />

<h2>3. Deterministic before intelligent</h2>

<blockquote><p><strong>Deterministic before intelligent.</strong></p></blockquote>

<table>
<tr><th>Question</th><th>Preferred method</th></tr>
<tr><td>Does <code>robots.txt</code> exist?</td><td>HTTP request</td></tr>
<tr><td>Does sitemap exist?</td><td>HTTP request + parser</td></tr>
<tr><td>Does OpenAPI exist?</td><td>HTTP request + schema validation</td></tr>
<tr><td>Is JSON valid?</td><td>JSON parser</td></tr>
<tr><td>Does declared endpoint exist in another document?</td><td>Exact matching</td></tr>
<tr><td>What does an undocumented endpoint mean?</td><td>AI-assisted inference</td></tr>
<tr><td>What does an API capability actually mean?</td><td>Human confirmation / assisted review</td></tr>
</table>

<p>AI is a <strong>copilot</strong>, not the authority responsible for the score.</p>

<hr />

<h2>4. Evidence is the missing layer</h2>

<p>A score without evidence is difficult to trust. <code>Documentation: 18/25</code> tells you almost nothing.</p>

<pre><code>AB-007  OpenAPI discoverability

STATUS: VERIFIED

Evidence:
GET https://api.example.com/openapi.json
HTTP 200
Content-Type: application/json

OpenAPI version:
3.1.0

Confidence:
1.00</code></pre>

<p><strong>Evidence is part of the measurement itself.</strong></p>

<hr />

<h2>5. Assertions connect evidence and scoring</h2>

<pre><code>{
  "rule_id": "AB-007",
  "status": "VERIFIED",
  "target": "https://api.example.com/openapi.json",
  "evidence": {
    "http_status": 200,
    "content_type": "application/json"
  },
  "confidence": 1.0
}</code></pre>

<p>Four states: <strong>VERIFIED</strong> (direct evidence), <strong>INFERRED</strong> (reasonable but insufficient), <strong>CONFLICT</strong> (two sources disagree), <strong>MISSING</strong> (not found).</p>

<hr />

<h2>6. Confidence is not the same as verification</h2>

<p>An LLM may be 94% confident an API supports refunds. Without machine-readable evidence, it stays INFERRED. The user can Confirm, Edit, or Reject.</p>

<hr />

<h2>7. Reproducibility matters</h2>

<pre><code>{
  "target": "https://api.example.com",
  "ruleset": "agent-readiness-v1.0",
  "scanner_version": "0.2.0",
  "timestamp": "...",
  "assertions": [...],
  "score": {
    "total": 76,
    "categories": {
      "discovery": 18,
      "documentation": 20,
      "authentication": 17,
      "machine_readability": 21
    }
  }
}</code></pre>

<img src="/images/blog/inside-an-agent-readiness-scanner/3s.webp" alt="Reproducibility infographic — three identical inputs converging into the same result" />

<hr />

<h2>8. Rules must be versioned</h2>

<p><code>Agent Readiness v1.0</code> must not silently become <code>v1.1</code>. Same target + same measurement state + same ruleset = reproducible result.</p>

<hr />

<h2>9. Why open rules do not destroy the product</h2>

<p>The moat is not secret rules. It's the standard installed inside the developer workflow: GitHub Actions, README badges, continuous monitoring, regression alerts.</p>

<hr />

<h2>10. The score should explain itself</h2>

<pre><code>+8  OpenAPI documentation detected
-12  New authentication issue detected
+0   Discovery unchanged
Result: 76 → 72</code></pre>

<hr />

<h2>11. From Measure to Prove to Improve</h2>

<p><strong>MEASURE (Scan) → PROVE (Evidence + Assertions) → IMPROVE (Fix / Review) → Measure again.</strong></p>

<img src="/images/blog/inside-an-agent-readiness-scanner/2s.webp" alt="Measure → Prove → Improve cycle diagram" />

<hr />

<h2>12. What AgentBadge should never claim</h2>

<p>AgentBadge measures Agent Readiness. It does not certify security, business correctness, or reliability.</p>

<blockquote><p><strong>Don't certify. Measure.</strong></p></blockquote>

<hr />

<h2>13. What this enables</h2>

<pre><code>npx @agentbadge/cli scan https://api.example.com</code></pre>

<p>CI enforcement, README badges, programmatic queries, vendor comparison.</p>

<hr />

<h2>14. The bigger idea</h2>

<p>Performance has metrics. Accessibility has checks. Security has scanners. The agentic web needs the same.</p>

<p><strong>Define the rules. Collect the evidence. Show the reasoning. Version the rules. Make the result reproducible.</strong></p>

<hr />

<h2>Related Articles</h2>

<ul>
<li><a href="/blog/what-is-agent-readiness">What Is Agent Readiness?</a> — Article 1</li>
<li><a href="/blog/why-ai-agents-fail-to-use-apis">Why AI Agents Fail to Use APIs</a> — Article 5</li>
<li><a href="/blog/what-ai-agent-needs-to-understand-api">What Does an AI Agent Need to Understand an API?</a> — Article 6</li>
<li><a href="/blog/why-openapi-isnt-enough">Why Your OpenAPI Spec Isn't Enough</a> — Article 7</li>
<li><a href="/blog/how-do-you-measure-agent-readiness">How Do You Measure Agent Readiness?</a> — Article 8</li>
</ul>

<p><em>For AI agents: the <a href="/agent-guide/articles/inside-an-agent-readiness-scanner">Agent Knowledge Layer</a> provides machine-readable access to this article's concepts, capabilities, and knowledge map.</em></p>`,
    externalLinks: [
      {
        platform: "devto",
        url: "https://dev.to/spread2009/inside-an-agent-readiness-scanner-rules-evidence-and-reproducibility-3j9k",
      },
      {
        platform: "medium",
        url: "",
      },
      {
        platform: "linkedin",
        url: "",
      },
      {
        platform: "hashnode",
        url: "",
      },
      {
        platform: "twitter",
        url: "",
      },
      {
        platform: "reddit",
        url: "",
      },
    ],
  };
