export const ErrorCodes = {
  // 400 — validation
  INVALID_JSON: "INVALID_JSON",
  MISSING_FIELDS: "MISSING_FIELDS",
  INVALID_DID_FORMAT: "INVALID_DID_FORMAT",
  INVALID_ENDPOINT_URL: "INVALID_ENDPOINT_URL",
  INVALID_PRICE: "INVALID_PRICE",
  INVALID_CAPABILITIES: "INVALID_CAPABILITIES",
  INVALID_PAGINATION: "INVALID_PAGINATION",
  SECRET_REJECTED: "SECRET_REJECTED",
  INVALID_INPUT: "INVALID_INPUT",
  WORK_REQUEST_NOT_FOUND: "WORK_REQUEST_NOT_FOUND",

  // 402 — payment
  PAYMENT_REQUIRED: "PAYMENT_REQUIRED",

  // 403 — passport/identity
  PASSPORT_NOT_FOUND: "PASSPORT_NOT_FOUND",
  PASSPORT_REVOKED: "PASSPORT_REVOKED",
  PASSPORT_OWNERSHIP_MISMATCH: "PASSPORT_OWNERSHIP_MISMATCH",
  PASSPORT_TYPE_REQUIRED: "PASSPORT_TYPE_REQUIRED",
  PASSPORT_TYPE_MISMATCH: "PASSPORT_TYPE_MISMATCH",
  WRONG_SIGNER: "WRONG_SIGNER",

  // 404 — not found
  AGENT_NOT_FOUND: "AGENT_NOT_FOUND",
  TASK_NOT_FOUND: "TASK_NOT_FOUND",
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",

  // 409 — conflict
  AGENTCARD_DID_CONFLICT: "AGENTCARD_DID_CONFLICT",
  TASK_ALREADY_CLAIMED: "TASK_ALREADY_CLAIMED",
  ESCROW_SIGNATURE_REQUIRED: "ESCROW_SIGNATURE_REQUIRED",

  // 422 — verification
  VERIFICATION_FAILED: "VERIFICATION_FAILED",

  // 429 — rate limit
  RATE_LIMITED: "RATE_LIMITED",

  // 500 — server
  INTERNAL_ERROR: "INTERNAL_ERROR",
  HCS_SUBMISSION_FAILED: "HCS_SUBMISSION_FAILED",
  MIRROR_NODE_UNAVAILABLE: "MIRROR_NODE_UNAVAILABLE",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
