import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { join } from "node:path";

// Read the static context.md file
const contextPath = join(__dirname, "../../src/server/agent-knowledge/context.md");
const contextMd = readFileSync(contextPath, "utf-8");

describe("SLICE-49-16: llms.txt and ai-sitemap.xml updates", () => {
  // Test llms.txt via catalog route content
  // We test the team section appended in catalog.ts which includes compliance endpoints

  describe("llms.txt compliance section", () => {
    // The llms.txt is generated by getLlmsTxt() from hedera-core + teamSection in catalog.ts
    // We verify the teamSection content is present in the catalog route source
    const catalogSource = readFileSync(
      join(__dirname, "../../src/server/routes/catalog.ts"),
      "utf-8",
    );

    it("mentions api-catalog endpoint in llms.txt section", () => {
      expect(catalogSource).toContain("api-catalog");
    });

    it("mentions oauth-protected-resource endpoint in llms.txt section", () => {
      expect(catalogSource).toContain("oauth-protected-resource");
    });

    it("mentions auth.md endpoint in llms.txt section", () => {
      expect(catalogSource).toContain("auth.md");
    });

    it("mentions agent-skills endpoint in llms.txt section", () => {
      expect(catalogSource).toContain("agent-skills/index.json");
    });

    it("mentions http-message-signatures-directory in llms.txt section", () => {
      expect(catalogSource).toContain("http-message-signatures-directory");
    });

    it("mentions check_compliance MCP tool in llms.txt section", () => {
      expect(catalogSource).toContain("check_compliance");
    });
  });

  describe("ai-sitemap.xml new entries", () => {
    // Verify buildAiSitemap includes new endpoints by checking well-known.ts source
    const wellKnownSource = readFileSync(
      join(__dirname, "../../src/server/routes/well-known.ts"),
      "utf-8",
    );

    it("includes api-catalog URL in sitemap resources", () => {
      expect(wellKnownSource).toContain("/.well-known/api-catalog");
    });

    it("includes oauth-protected-resource URL in sitemap resources", () => {
      expect(wellKnownSource).toContain("/.well-known/oauth-protected-resource");
    });

    it("includes auth.md URL in sitemap resources", () => {
      expect(wellKnownSource).toContain("/auth.md");
    });

    it("includes agent-skills URL in sitemap resources", () => {
      expect(wellKnownSource).toContain("/.well-known/agent-skills/index.json");
    });

    it("includes http-message-signatures-directory URL in sitemap resources", () => {
      expect(wellKnownSource).toContain("/.well-known/http-message-signatures-directory");
    });
  });
});

describe("SLICE-49-17: Agent Guide compliance section", () => {
  it("context.md contains Compliance Checking section", () => {
    expect(contextMd).toContain("## Compliance Checking");
  });

  it("context.md mentions check_compliance MCP tool", () => {
    expect(contextMd).toContain("check_compliance");
  });

  it("context.md shows example MCP call", () => {
    expect(contextMd).toContain('"tool": "check_compliance"');
  });

  it("context.md describes response structure", () => {
    expect(contextMd).toContain("score");
    expect(contextMd).toContain("rules_checked");
    expect(contextMd).toContain("rules_passed");
    expect(contextMd).toContain("rules_failed");
  });

  it("context.md lists compliance endpoints", () => {
    expect(contextMd).toContain("api-catalog");
    expect(contextMd).toContain("oauth-protected-resource");
    expect(contextMd).toContain("auth.md");
    expect(contextMd).toContain("agent-skills/index.json");
    expect(contextMd).toContain("http-message-signatures-directory");
  });

  it("context.md links to isitagentready.com", () => {
    expect(contextMd).toContain("isitagentready.com");
  });
});
