#!/usr/bin/env bun
// Generates docs/architecture-graph.md — a mermaid module-dependency diagram
// for hackathon/server/src. Nodes = top-level modules (server/routes,
// server/lib, views, agent-readiness, ...). Edges = import relationships.
// Run: bun run scripts/arch-graph.mts   (from hackathon/server/)

import { readdirSync, readFileSync, writeFileSync, statSync, mkdirSync } from "node:fs";
import { join, relative, dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const SRC = resolve(HERE, "../src");
const OUT = resolve(HERE, "../docs/architecture-graph.md");

function* walk(dir: string): Generator<string> {
  for (const e of readdirSync(dir)) {
    const p = join(dir, e);
    if (statSync(p).isDirectory()) yield* walk(p);
    else if (p.endsWith(".ts")) yield p;
  }
}

// Map a src-relative path to its module node id.
// Depth-2 for server/* and agent-readiness/*, depth-1 otherwise.
function moduleOf(rel: string): string {
  const parts = rel.split("/");
  if (parts[0] === "server" && parts.length > 2)
    return `server/${parts[1]}`;
  if (parts[0] === "agent-readiness" && parts.length > 2)
    return `agent-readiness/${parts[1]}`;
  return parts[0].replace(/\.ts$/, "");
}

const IMPORT_RE = /import\s+(?:type\s+)?(?:[^"']*from\s+)?["']([^"']+)["']/g;
const edges = new Map<string, Set<string>>();

for (const file of walk(SRC)) {
  const rel = relative(SRC, file);
  const from = moduleOf(rel);
  const src = readFileSync(file, "utf8");
  for (const m of src.matchAll(IMPORT_RE)) {
    const spec = m[1];
    let to: string | null = null;
    if (spec.startsWith("@agentbadge/")) {
      to = `pkg:${spec.replace("@agentbadge/", "")}`;
    } else if (spec.startsWith(".")) {
      const target = resolve(dirname(join(SRC, rel)), spec);
      const trel = relative(SRC, target).replace(/\.(ts|js)$/, "").replace(/\/index$/, "");
      if (trel.startsWith("..")) continue; // escapes src/ (tests, repo root)
      to = moduleOf(trel);
    }
    if (to && to !== from) {
      if (!edges.has(from)) edges.set(from, new Set());
      edges.get(from)!.add(to);
    }
  }
}

const nodeId = (n: string) => n.replace(/[^a-zA-Z0-9]/g, "_");
const lines: string[] = ["flowchart LR"];
const pkgNodes = new Set<string>();
for (const [from, tos] of [...edges.entries()].sort()) {
  for (const to of [...tos].sort()) {
    if (to.startsWith("pkg:")) pkgNodes.add(to);
    lines.push(`  ${nodeId(from)}["${from}"] --> ${nodeId(to)}["${to.replace("pkg:", "pkg: ")}"]`);
  }
}

const md = `# Architecture Graph — hackathon/server/src

Generated by \`scripts/arch-graph.mts\`. Do not edit by hand —
regenerate after structural changes (\`bun run arch:graph\`). Output is
deterministic: CI fails on any diff (\`bun run arch:graph:check\`).

\`\`\`mermaid
${lines.join("\n")}
\`\`\`

- Nodes are top-level modules (\`server/routes\`, \`views\`, \`agent-readiness/*\`, ...).
- \`pkg:*\` nodes are \`@agentbadge/*\` packages — dependency direction is
  always server → package, never the reverse.
- ${edges.size} modules import across boundaries; ${pkgNodes.size} packages consumed.
`;

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, md);
console.log(`wrote ${OUT} (${edges.size} modules, ${pkgNodes.size} packages)`);
