/**
 * SLICE-182-6: generate openapi/openapi.yaml from the live app spec and
 * commit it — agents read the spec without hitting the API
 * (CiteFlow pattern). `--check` mode verifies the committed artifact
 * matches the generator output and exits 1 on drift (CI gate).
 *
 *   bun scripts/gen-openapi.ts          # write openapi/openapi.yaml
 *   bun scripts/gen-openapi.ts --check  # verify, no write
 */

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";
import { stringify } from "yaml";

// Canonical server URL in the committed artifact — set before the app
// module loads (openApiConfig reads process.env at import time; dotenv
// never overrides an already-set var).
process.env.BASE_URL ??= "https://agentbadge.xyz";

const { createApp } = await import("../src/server/index");

const OUT = "openapi/openapi.yaml";
const HEADER = `# Generated by scripts/gen-openapi.ts — do not hand-edit.
# Regenerate: bun run gen:openapi · Verify: bun run check:openapi
`;

const app = createApp();
const res = await app.request("/openapi.json");
if (res.status !== 200) {
  console.error(`gen-openapi: /openapi.json answered ${res.status}`);
  process.exit(3);
}
const spec = await res.json();
const yaml = HEADER + stringify(spec);

if (process.argv.includes("--check")) {
  let existing = "";
  try {
    existing = readFileSync(OUT, "utf-8");
  } catch {
    console.error(`gen-openapi --check: ${OUT} missing — run bun run gen:openapi`);
    process.exit(2);
  }
  if (existing !== yaml) {
    console.error(
      `gen-openapi --check: ${OUT} is stale — run bun run gen:openapi and commit`,
    );
    process.exit(1);
  }
  console.log(`gen-openapi --check: ${OUT} up to date`);
  process.exit(0);
}

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, yaml);
console.log(`gen-openapi: wrote ${OUT}`);
process.exit(0);
